
            <a name="automated_metrics" class="anchor-point"></a>
            <h3 id="automated-metrics-heading">Automated Metrics <a class="info-icon" href="<?php echo site_url('docs'); ?>#automated_metrics"><span class="glyphicon glyphicon-info-sign"></span></a></h3>


            <?php if (empty($office_campaign->bureaudirectory_status) && empty($office_campaign->governanceboard_status)): ?>
                <p>No automated metrics are currently available for this milestone</p>
            <?php else: ?> 
                <p>These metrics are generated by an automated analysis that runs every 24 hours until the end of the quarter at which point they become a historical snapshot</p>
            <?php endif; ?> 



            <?php if (!empty($office_campaign->bureaudirectory_status)): ?>
                <a name="pdl_bureaudirectory" class="anchor-point"></a>              
            <?php endif; ?>


            <?php if (!empty($office_campaign->bureaudirectory_status)): ?>

                <div id="bureaudirectory-heading" class="panel panel-default">
                    <div class="panel-heading">
                        /digitalstrategy/bureaudirectory.json 
                        <a class="info-icon" href="<?php echo site_url('docs') . '#bureaudirectory' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>             
                    </div>

                    <table class="table table-striped table-hover">		

                        <tr>
                            <th>Expected bureaudirectory.json URL</th>
                            <td>
                                <?php if (!empty($office_campaign->bureaudirectory_status->expected_url)): ?>
                                    <a href="<?php echo $office_campaign->bureaudirectory_status->expected_url ?>"><?php echo $office_campaign->bureaudirectory_status->expected_url ?></a>
                                <?php endif; ?>

                                <?php
                                $http_code = (!empty($office_campaign->bureaudirectory_status->http_code)) ? $office_campaign->bureaudirectory_status->http_code : 0;

                                switch ($http_code) {
                                    case 404:
                                        $status_color = 'danger';
                                        break;
                                    case 200:
                                        $status_color = 'success';
                                        break;
                                    case 0:
                                        $status_color = '';
                                        break;
                                    default:
                                        $status_color = 'warning';
                                }

                                if (!empty($office_campaign->bureaudirectory_status->content_type)) {
                                    if (strpos($office_campaign->bureaudirectory_status->content_type, 'application/json') !== false) {
                                        $mime_color = 'success';
                                    } else {
                                        $mime_color = 'danger';
                                    }
                                } else {
                                    $mime_color = 'danger';
                                }
                                ?>

                            </td>
                        </tr>

                        <tr>
                            <th>Resolved bureaudirectory.json URL</th>
                            <td>
                                <a href="<?php echo $office_campaign->bureaudirectory_status->url ?>"><?php echo $office_campaign->bureaudirectory_status->url ?></a>
                            </td>
                        </tr>	

                        <tr>
                            <th>Redirects</th>
                            <td>
                                <?php if (!empty($office_campaign->bureaudirectory_status->redirect_count)): ?>
                                                            <span class="text-<?php echo ($office_campaign->bureaudirectory_status->redirect_count > 5) ? 'danger' : 'warning' ?>">
                                    <?php echo $office_campaign->bureaudirectory_status->redirect_count . ' redirects'; ?>
                                                            </span>	
                                    <?php if ($office_campaign->bureaudirectory_status->redirect_count > 5): ?>			
                                                                <span style="color:#ccc"> (stops tracking after 6)</span>
                                    <?php endif; ?>			        		
                                <?php endif; ?>			
                            </td>
                        </tr>		

                        <tr class="<?php echo $status_color; ?>">
                            <th>HTTP Status</th>
                            <td>
                                <span class="text-<?php echo $status_color; ?>">
                                    <?php echo $office_campaign->bureaudirectory_status->http_code ?>
                                </span>			
                            </td>
                        </tr>				

                        <tr class="<?php echo $mime_color; ?>">
                            <th>Content Type</th>
                            <td>
                                <span class="text-<?php echo $mime_color; ?>">
                                    <?php echo $office_campaign->bureaudirectory_status->content_type ?>
                                </span>			
                            </td>
                        </tr>	

                        <?php
                        if ($http_code == 200 && $bureau_directory = curl_from_json($office_campaign->bureaudirectory_status->url, false, true)) {
                            $valid_json = true;
                        } else {
                            $valid_json = false;
                        }
                        ?>

                        <tr class="<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                            <th>Valid JSON</th>
                            <td>
                                <span class="text-<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                                <?php
                                if ($valid_json == true)
                                    echo 'Valid';
                                if (($valid_json == false && $valid_json !== null) || ($office_campaign->bureaudirectory_status->http_code == 200 && $valid_json != true))
                                    echo 'Invalid <span><a href="http://jsonlint.com/">Check a JSON Validator</a></span>';
                                ?>
                            </td>
                        </tr>        	

                        <?php if (!empty($office_campaign->bureaudirectory_status->filetime) && $office_campaign->bureaudirectory_status->filetime > 0): ?>
                            <tr>
                                <th>Last modified</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->bureaudirectory_status->filetime) ?>
                                    </span>         
                                </td>
                            </tr>   
                        <?php endif; ?> 

                        <?php if (!empty($office_campaign->bureaudirectory_status->last_crawl)): ?>
                            <tr>
                                <th>Last crawl</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->bureaudirectory_status->last_crawl) ?>
                                    </span>         
                                </td>
                            </tr>   
                        <?php endif; ?>  

                    </table>
                </div>
            <?php endif; ?>

            <?php if ($valid_json == true && !empty($bureau_directory)): ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        Bureau IT Leadership Directory
                        <a class="info-icon" href="<?php echo site_url('docs') . '#bureaudirectory_excerpts' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>                  
                    </div>
                    <div style="padding : 1em;">
                        <?php
                        $sections = array("1.2.4" => "edi_schedule_delivered",
                            "1.2.5" => "schedule",
                            "1.2.6" => "pe_feedback_specified",
                            "1.2.7" => "ps_publication_process");

                        if (!empty($bureau_directory->generated)) {
                            if ($published_date = strtotime($bureau_directory->generated)) {
                                $published_date = date("l, d-M-Y H:i:s T", $published_date);
                                echo '<h2><span style="color:#666">Date specified: </span>' . "$published_date</h2>";
                            }
                        }

                        if (!empty($office_campaign->bureaudirectory_status->filetime) && $office_campaign->bureaudirectory_status->filetime > 0) {
                            echo 'Date of bureaudirectory.json file: ' . date("l, d-M-Y H:i:s T", $office_campaign->bureaudirectory_status->filetime);
                        }

                        echo "<hr>";
                        ?>

                        <?php
                        if (!empty($bureau_directory->items)) {

                            foreach ($bureau_directory->items as $item) {
                                if (!empty($sections[$item->id])) {

                                    echo "<a name=\"{$sections[$item->id]}\" class=\"anchor-point\"></a>";
                                    echo "<h3>{$item->id} {$item->text}</h3>";

                                    if ($item->multiple === false) {
                                        echo "<h4>{$item->fields[0]->label}</h4>";
                                        echo '<br>';
                                        echo '<pre style="white-space: pre-wrap; word-break: keep-all; ">' . $item->fields[0]->value . '</pre>';
                                    } else {

                                        $columns = count($item->fields);
                                        $rows = count($item->fields[0]->value);



                                        for ($row = 0; $row < $rows; $row++) {

                                            echo '<table class="table table-striped table-hover" style="margin-bottom : 4em; border-bottom : 3px solid #ccc">';

                                            for ($column = 0; $column < $columns; $column++) {
                                                echo '<tr>';
                                                echo '<th class="col-sm-2 col-md-2 col-lg-2">' . "{$item->fields[$column]->label}</th>";

                                                echo '<td class="col-sm-10 col-md-10 col-lg-10">';
                                                if (!empty($item->fields[$column]->value[$row])) {
                                                    echo $item->fields[$column]->value[$row];
                                                }
                                                echo "</td>";

                                                echo "</tr>";
                                            }

                                            echo '</table>';
                                        }
                                    }

                                    echo '<hr>';
                                }
                            }
                        }
                        ?>

                    </div>
                </div>

            <?php endif; ?>       

            <?php if (!empty($office_campaign->governanceboard_status)): ?>

                <div id="governanceboard-heading" class="panel panel-default">
                    <div class="panel-heading">
                        /digitalstrategy/governanceboards.json 
                        <a class="info-icon" href="<?php echo site_url('docs') . '#governanceboard' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>             
                    </div>

                    <table class="table table-striped table-hover">		

                        <tr>
                            <th>Expected governanceboards.json URL</th>
                            <td>
                                <?php if (!empty($office_campaign->governanceboard_status->expected_url)): ?>
                                    <a href="<?php echo $office_campaign->governanceboard_status->expected_url ?>"><?php echo $office_campaign->governanceboard_status->expected_url ?></a>
                                <?php endif; ?>

                                <?php
                                $http_code = (!empty($office_campaign->governanceboard_status->http_code)) ? $office_campaign->governanceboard_status->http_code : 0;

                                switch ($http_code) {
                                    case 404:
                                        $status_color = 'danger';
                                        break;
                                    case 200:
                                        $status_color = 'success';
                                        break;
                                    case 0:
                                        $status_color = '';
                                        break;
                                    default:
                                        $status_color = 'warning';
                                }

                                if (!empty($office_campaign->governanceboard_status->content_type)) {
                                    if (strpos($office_campaign->governanceboard_status->content_type, 'application/json') !== false) {
                                        $mime_color = 'success';
                                    } else {
                                        $mime_color = 'danger';
                                    }
                                } else {
                                    $mime_color = 'danger';
                                }
                                ?>

                            </td>
                        </tr>

                        <tr>
                            <th>Resolved governanceboards.json URL</th>
                            <td>
                                <a href="<?php echo $office_campaign->governanceboard_status->url ?>"><?php echo $office_campaign->governanceboard_status->url ?></a>
                            </td>
                        </tr>	

                        <tr>
                            <th>Redirects</th>
                            <td>
                                <?php if (!empty($office_campaign->governanceboard_status->redirect_count)): ?>
                                                            <span class="text-<?php echo ($office_campaign->governanceboard_status->redirect_count > 5) ? 'danger' : 'warning' ?>">
                                    <?php echo $office_campaign->governanceboard_status->redirect_count . ' redirects'; ?>
                                                            </span>	
                                    <?php if ($office_campaign->governanceboard_status->redirect_count > 5): ?>			
                                                                <span style="color:#ccc"> (stops tracking after 6)</span>
                                    <?php endif; ?>			        		
                                <?php endif; ?>			
                            </td>
                        </tr>		

                        <tr class="<?php echo $status_color; ?>">
                            <th>HTTP Status</th>
                            <td>
                                <span class="text-<?php echo $status_color; ?>">
                                    <?php echo $office_campaign->governanceboard_status->http_code ?>
                                </span>			
                            </td>
                        </tr>				

                        <tr class="<?php echo $mime_color; ?>">
                            <th>Content Type</th>
                            <td>
                                <span class="text-<?php echo $mime_color; ?>">
                                    <?php echo $office_campaign->governanceboard_status->content_type ?>
                                </span>			
                            </td>
                        </tr>	

                        <?php
                        if ($http_code == 200 && $governance_board = curl_from_json($office_campaign->governanceboard_status->url, false, true)) {
                            $valid_json = true;
                        } else {
                            $valid_json = false;
                        }
                        ?>

                        <tr class="<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                            <th>Valid JSON</th>
                            <td>
                                <span class="text-<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                                <?php
                                if ($valid_json == true)
                                    echo 'Valid';
                                if (($valid_json == false && $valid_json !== null) || ($office_campaign->governanceboard_status->http_code == 200 && $valid_json != true))
                                    echo 'Invalid <span><a href="http://jsonlint.com/">Check a JSON Validator</a></span>';
                                ?>
                            </td>
                        </tr>        	

                        <?php if (!empty($office_campaign->governanceboard_status->filetime) && $office_campaign->governanceboard_status->filetime > 0): ?>
                            <tr>
                                <th>Last modified</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->governanceboard_status->filetime) ?>
                                    </span>         
                                </td>
                            </tr>   
                        <?php endif; ?> 

                        <?php if (!empty($office_campaign->governanceboard_status->last_crawl)): ?>
                            <tr>
                                <th>Last crawl</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->governanceboard_status->last_crawl) ?>
                                    </span>         
                                </td>
                            </tr>   
                        <?php endif; ?>  

                    </table>
                </div>
            <?php endif; ?>

            <?php if ($valid_json == true && !empty($governance_board)): ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        Governance Boards 
                        <a class="info-icon" href="<?php echo site_url('docs') . '#governanceboard_excerpts' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>                  
                    </div>
                    <div style="padding : 1em;">
                        <?php
                        $sections = array("1.2.4" => "edi_schedule_delivered",
                            "1.2.5" => "schedule",
                            "1.2.6" => "pe_feedback_specified",
                            "1.2.7" => "ps_publication_process");

                        if (!empty($governance_board->generated)) {
                            if ($published_date = strtotime($governance_board->generated)) {
                                $published_date = date("l, d-M-Y H:i:s T", $published_date);
                                echo '<h2><span style="color:#666">Date specified: </span>' . "$published_date</h2>";
                            }
                        }

                        if (!empty($office_campaign->governanceboard_status->filetime) && $office_campaign->governanceboard_status->filetime > 0) {
                            echo 'Date of governanceboard.json file: ' . date("l, d-M-Y H:i:s T", $office_campaign->governanceboard_status->filetime);
                        }

                        echo "<hr>";
                        ?>

                        <?php
                        if (!empty($governance_board->items)) {

                            foreach ($governance_board->items as $item) {
                                if (!empty($sections[$item->id])) {

                                    echo "<a name=\"{$sections[$item->id]}\" class=\"anchor-point\"></a>";
                                    echo "<h3>{$item->id} {$item->text}</h3>";

                                    if ($item->multiple === false) {
                                        echo "<h4>{$item->fields[0]->label}</h4>";
                                        echo '<br>';
                                        echo '<pre style="white-space: pre-wrap; word-break: keep-all; ">' . $item->fields[0]->value . '</pre>';
                                    } else {

                                        $columns = count($item->fields);
                                        $rows = count($item->fields[0]->value);



                                        for ($row = 0; $row < $rows; $row++) {

                                            echo '<table class="table table-striped table-hover" style="margin-bottom : 4em; border-bottom : 3px solid #ccc">';

                                            for ($column = 0; $column < $columns; $column++) {
                                                echo '<tr>';
                                                echo '<th class="col-sm-2 col-md-2 col-lg-2">' . "{$item->fields[$column]->label}</th>";

                                                echo '<td class="col-sm-10 col-md-10 col-lg-10">';
                                                if (!empty($item->fields[$column]->value[$row])) {
                                                    echo $item->fields[$column]->value[$row];
                                                }
                                                echo "</td>";

                                                echo "</tr>";
                                            }

                                            echo '</table>';
                                        }
                                    }

                                    echo '<hr>';
                                }
                            }
                        }
                        ?>

                    </div>
                </div>

            <?php endif; ?>       
                