
            <a name="automated_metrics" class="anchor-point"></a>
            <h3 id="automated-metrics-heading">Automated Metrics <a class="info-icon" href="<?php echo site_url('docs'); ?>#automated_metrics"><span class="glyphicon glyphicon-info-sign"></span></a></h3>


            <?php if (empty($office_campaign->bureaudirectory_status) && empty($office_campaign->governanceboard_status)): ?>
                <p>No automated metrics are currently available for this milestone</p>
            <?php else: ?>
                <p>These metrics are generated by an automated analysis that runs every 24 hours until the end of the quarter at which point they become a historical snapshot</p>
            <?php endif; ?>



            <?php if (!empty($office_campaign->bureaudirectory_status)): ?>
                <a name="pdl_bureaudirectory" class="anchor-point"></a>
            <?php endif; ?>


            <?php if (!empty($office_campaign->bureaudirectory_status)): ?>

                <div id="bureaudirectory-heading" class="panel panel-default">
                    <div class="panel-heading">
                        /digitalstrategy/bureaudirectory.json
                        <a class="info-icon" href="<?php echo site_url('docs') . '#bureaudirectory' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>
                    </div>

                    <table class="table table-striped table-hover">

                        <tr>
                            <th>Expected bureaudirectory.json URL</th>
                            <td>
                                <?php if (!empty($office_campaign->bureaudirectory_status->expected_url)): ?>
                                    <a href="<?php echo $office_campaign->bureaudirectory_status->expected_url ?>"><?php echo $office_campaign->bureaudirectory_status->expected_url ?></a>
                                <?php endif; ?>

                                <?php
                                $http_code = (!empty($office_campaign->bureaudirectory_status->http_code)) ? $office_campaign->bureaudirectory_status->http_code : 0;

                                switch ($http_code) {
                                    case 404:
                                        $status_color = 'danger';
                                        break;
                                    case 200:
                                        $status_color = 'success';
                                        break;
                                    case 0:
                                        $status_color = '';
                                        break;
                                    default:
                                        $status_color = 'warning';
                                }

                                if (!empty($office_campaign->bureaudirectory_status->content_type)) {
                                    if (strpos($office_campaign->bureaudirectory_status->content_type, 'application/json') !== false) {
                                        $mime_color = 'success';
                                    } else {
                                        $mime_color = 'danger';
                                    }
                                } else {
                                    $mime_color = 'danger';
                                }
                                ?>

                            </td>
                        </tr>

                        <tr>
                            <th>Resolved bureaudirectory.json URL</th>
                            <td>
                                <a href="<?php echo $office_campaign->bureaudirectory_status->url ?>"><?php echo $office_campaign->bureaudirectory_status->url ?></a>
                            </td>
                        </tr>

                        <tr>
                            <th>Redirects</th>
                            <td>
                                <?php if (!empty($office_campaign->bureaudirectory_status->redirect_count)): ?>
                                                            <span class="text-<?php echo ($office_campaign->bureaudirectory_status->redirect_count > 5) ? 'danger' : 'warning' ?>">
                                    <?php echo $office_campaign->bureaudirectory_status->redirect_count . ' redirects'; ?>
                                                            </span>
                                    <?php if ($office_campaign->bureaudirectory_status->redirect_count > 5): ?>
                                                                <span style="color:#ccc"> (stops tracking after 6)</span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </td>
                        </tr>

                        <tr class="<?php echo $status_color; ?>">
                            <th>HTTP Status</th>
                            <td>
                                <span class="text-<?php echo $status_color; ?>">
                                    <?php echo $office_campaign->bureaudirectory_status->http_code ?>
                                </span>
                            </td>
                        </tr>

                        <tr class="<?php echo $mime_color; ?>">
                            <th>Content Type</th>
                            <td>
                                <span class="text-<?php echo $mime_color; ?>">
                                    <?php echo $office_campaign->bureaudirectory_status->content_type ?>
                                </span>
                            </td>
                        </tr>

                        <?php
                        // TO DO - when we have agency files at a valid url, put the checks back
                        if(property_exists($office_campaign->bureaudirectory_status, "valid_json")) {
                           $valid_json = $office_campaign->bureaudirectory_status->valid_json;
                        }
                        else if ($http_code == 200 && $bureau_directory = curl_from_json($office_campaign->bureaudirectory_status->url, false, true)) {
                            $valid_json = true;
                        } else {
                            $valid_json = false;
                        }
                        ?>

                        <tr class="<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                            <th>Valid JSON</th>
                            <td>
                                <span class="text-<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                                <?php
                                if ($valid_json == true)
                                    echo 'Valid';
                                if (($valid_json == false && $valid_json !== null) || ($office_campaign->bureaudirectory_status->http_code == 200 && $valid_json != true))
                                    echo 'Invalid <span><a href="http://jsonlint.com/">Check a JSON Validator</a></span>';
                                ?>
                            </td>
                        </tr>

                        <?php if (!empty($office_campaign->bureaudirectory_status->filetime) && $office_campaign->bureaudirectory_status->filetime > 0): ?>
                            <tr>
                                <th>Last modified</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->bureaudirectory_status->filetime) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if (!empty($office_campaign->bureaudirectory_status->last_crawl)): ?>
                            <tr>
                                <th>Last crawl</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->bureaudirectory_status->last_crawl) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leadership)): ?>
                            <tr>
                                <th id="pa_bureau_it_leadership">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_bureau_it_leadership' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    Bureau IT Leadership file exists and conforms to schema?
                                </th>
                                <td>
                                    <a name="pa_bureau_it_leadership" class="anchor-point"></a>
                                    <?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leadership ? 'Yes' : 'No';?>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leaders)): ?>
                            <tr>
                                <th id="pa_bureau_it_leaders">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_bureau_it_leaders' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    # Bureau IT Leaders
                                </th>
                                <td>
                                    <a name="pa_bureau_it_leaders" class="anchor-point"></a>
                                    <?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leaders;?>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->bureaudirectory_status->tracker_fields->pa_key_bureau_it_leaders)): ?>
                            <tr>
                                <th id="pa_key_bureau_it_leaders">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_key_bureau_it_leaders' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    # Key Bureau IT Leaders
                                </th>
                                <td>
                                    <a name="pa_key_bureau_it_leaders" class="anchor-point"></a>
                                    <?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_key_bureau_it_leaders;?>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->bureaudirectory_status->tracker_fields->pa_political_appointees)): ?>
                            <tr>
                                <th id="pa_political_appointees">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_political_appointees' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    # Political Appointees
                                </th>
                                <td>
                                    <a name="pa_political_appointees" class="anchor-point"></a>
                                    <?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_political_appointees;?>/<?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leaders;?>
                                    (<?php echo intval($office_campaign->bureaudirectory_status->tracker_fields->pa_political_appointees / $office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leaders * 100);?>%)
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leadership_link)): ?>
                            <tr>
                                <th id="pa_bureau_it_leadership_link">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_bureau_it_leadership_link' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    Link to Bureau IT Leadership directory
                                </th>
                                <td>
                                    <a name="pa_bureau_it_leadership_link" class="anchor-point"></a>
                                    <a href="<?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leadership_link;?>">
                                        <?php echo $office_campaign->bureaudirectory_status->tracker_fields->pa_bureau_it_leadership_link;?>
                                    </a>
                                </td>
                            </tr>
                        <?php endif; ?>

                    </table>
                </div>
            <?php endif; ?>

            <?php if ($valid_json == true && !empty($bureau_directory)): ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Bureau IT Leadership Directory
                        <a class="info-icon" href="<?php echo site_url('docs') . '#bureaudirectory_excerpts' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>
                    </div>
                    <div style="padding : 1em;">
                        <?php
                        $sections = array("1.2.4" => "edi_schedule_delivered",
                            "1.2.5" => "schedule",
                            "1.2.6" => "pe_feedback_specified",
                            "1.2.7" => "ps_publication_process");

                        if (!empty($bureau_directory->generated)) {
                            if ($published_date = strtotime($bureau_directory->generated)) {
                                $published_date = date("l, d-M-Y H:i:s T", $published_date);
                                echo '<h2><span style="color:#666">Date specified: </span>' . "$published_date</h2>";
                            }
                        }

                        if (!empty($office_campaign->bureaudirectory_status->filetime) && $office_campaign->bureaudirectory_status->filetime > 0) {
                            echo 'Date of bureaudirectory.json file: ' . date("l, d-M-Y H:i:s T", $office_campaign->bureaudirectory_status->filetime);
                        }

                        ?>
                        <?php
                        if (!empty($bureau_directory->leaders)) {
                            echo '<table class="table table-striped table-hover" style="border-bottom : 3px solid #ccc">';
                            echo "<tr>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Bureau Code</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Bureau Name</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>First Name</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Last Name</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Key Bureau CIO</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Employment Type</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Employment Type Other</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Type of Appointment</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Other Responsibilities</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Rating Official Title</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Reviewing Official Title</th>";
                            echo "</tr>\n";
                            foreach($bureau_directory->leaders as $leader) {
                                echo "<tr>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->bureauCode . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . (isset($leader->bureauName) ? $leader->bureauName : "Agency-wide")  . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->firstName . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->lastName . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->keyBureauCIO . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->employmentType . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . (isset($leader->employmentTypeOther) ? $leader->employmentTypeOther : "") . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->typeOfAppointment . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . (isset($leader->otherResponsibilities) ? $leader->otherResponsibilities : "") . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . $leader->evaluationRatingOfficialTitle . "</td>";
                                echo "<td class='col-sm-11 col-md-11 col-lg-11'>" . (isset($leader->evaluationReviewingOfficialTitle) ? $leader->evaluationReviewingOfficialTitle : "") . "</td>";
                                echo "</tr>\n";
                            }
                            echo '</table>';
                        }
                        ?>

                    </div>
                </div>
            <?php endif; ?>

            <?php if (!empty($office_campaign->governanceboard_status)): ?>

                <div id="governanceboard-heading" class="panel panel-default">
                    <div class="panel-heading">
                        /digitalstrategy/governanceboards.json
                        <a class="info-icon" href="<?php echo site_url('docs') . '#governanceboard' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>
                    </div>

                    <table class="table table-striped table-hover">

                        <tr>
                            <th>Expected governanceboards.json URL</th>
                            <td>
                                <?php if (!empty($office_campaign->governanceboard_status->expected_url)): ?>
                                    <a href="<?php echo $office_campaign->governanceboard_status->expected_url ?>"><?php echo $office_campaign->governanceboard_status->expected_url ?></a>
                                <?php endif; ?>

                                <?php
                                $http_code = (!empty($office_campaign->governanceboard_status->http_code)) ? $office_campaign->governanceboard_status->http_code : 0;

                                switch ($http_code) {
                                    case 404:
                                        $status_color = 'danger';
                                        break;
                                    case 200:
                                        $status_color = 'success';
                                        break;
                                    case 0:
                                        $status_color = '';
                                        break;
                                    default:
                                        $status_color = 'warning';
                                }

                                if (!empty($office_campaign->governanceboard_status->content_type)) {
                                    if (strpos($office_campaign->governanceboard_status->content_type, 'application/json') !== false) {
                                        $mime_color = 'success';
                                    } else {
                                        $mime_color = 'danger';
                                    }
                                } else {
                                    $mime_color = 'danger';
                                }
                                ?>

                            </td>
                        </tr>

                        <tr>
                            <th>Resolved governanceboards.json URL</th>
                            <td>
                                <a href="<?php echo $office_campaign->governanceboard_status->url ?>"><?php echo $office_campaign->governanceboard_status->url ?></a>
                            </td>
                        </tr>

                        <tr>
                            <th>Redirects</th>
                            <td>
                                <?php if (!empty($office_campaign->governanceboard_status->redirect_count)): ?>
                                                            <span class="text-<?php echo ($office_campaign->governanceboard_status->redirect_count > 5) ? 'danger' : 'warning' ?>">
                                    <?php echo $office_campaign->governanceboard_status->redirect_count . ' redirects'; ?>
                                                            </span>
                                    <?php if ($office_campaign->governanceboard_status->redirect_count > 5): ?>
                                                                <span style="color:#ccc"> (stops tracking after 6)</span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </td>
                        </tr>

                        <tr class="<?php echo $status_color; ?>">
                            <th>HTTP Status</th>
                            <td>
                                <span class="text-<?php echo $status_color; ?>">
                                    <?php echo $office_campaign->governanceboard_status->http_code ?>
                                </span>
                            </td>
                        </tr>

                        <tr class="<?php echo $mime_color; ?>">
                            <th>Content Type</th>
                            <td>
                                <span class="text-<?php echo $mime_color; ?>">
                                    <?php echo $office_campaign->governanceboard_status->content_type ?>
                                </span>
                            </td>
                        </tr>

                        <?php
                        // TO DO - when we have agency files at a valid url, put the checks back
                        if(property_exists($office_campaign->governanceboard_status, "valid_json")) {
                          $valid_json = $office_campaign->governanceboard_status->valid_json;
                        }
                        else if ($http_code == 200 && $governance_board = curl_from_json($office_campaign->governanceboard_status->url, false, true)) {
                            $valid_json = true;
                        } else {
                            $valid_json = false;
                        }
                        ?>

                        <tr class="<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                            <th>Valid JSON</th>
                            <td>
                                <span class="text-<?php echo ($valid_json == true) ? 'success' : 'danger' ?>">
                                <?php
                                if ($valid_json == true)
                                    echo 'Valid';
                                if (($valid_json == false && $valid_json !== null) || ($office_campaign->governanceboard_status->http_code == 200 && $valid_json != true))
                                    echo 'Invalid <span><a href="http://jsonlint.com/">Check a JSON Validator</a></span>';
                                ?>
                            </td>
                        </tr>

                        <?php if (!empty($office_campaign->governanceboard_status->filetime) && $office_campaign->governanceboard_status->filetime > 0): ?>
                            <tr>
                                <th>Last modified</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->governanceboard_status->filetime) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if (!empty($office_campaign->governanceboard_status->last_crawl)): ?>
                            <tr>
                                <th>Last crawl</th>
                                <td>
                                    <span>
                                        <?php echo date("l, d-M-Y H:i:s T", $office_campaign->governanceboard_status->last_crawl) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->governanceboard_status->tracker_fields->pa_cio_governance_board)): ?>
                            <tr>
                                <th id="pa_cio_governance_board">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_cio_governance_board' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    CIO Governance Board file exists and conforms to schema?
                                </th>
                                <td>
                                    <a name="pa_cio_governance_board" class="anchor-point"></a>
                                    <?php echo $office_campaign->governanceboard_status->tracker_fields->pa_cio_governance_board ? 'Yes' : 'No';?>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->governanceboard_status->tracker_fields->pa_mapped_to_program_inventory)): ?>
                            <tr>
                                <th id="pa_mapped_to_program_inventory">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_mapped_to_program_inventory' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    % Mapped to Federal Program Inventory
                                </th>
                                <td>
                                    <a name="pa_mapped_to_program_inventory" class="anchor-point"></a>
                                    <?php if($office_campaign->governanceboard_status->tracker_fields->pa_ref_program_inventory != 0) {
                                            echo intval($office_campaign->governanceboard_status->tracker_fields->pa_mapped_to_program_inventory / $office_campaign->governanceboard_status->tracker_fields->pa_ref_program_inventory * 100) . "%";
                                          } ?>
                                </td>
                            </tr>
                        <?php endif; ?>

                        <?php if(isset($office_campaign->governanceboard_status->tracker_fields->pa_cio_governance_board_link)): ?>
                            <tr>
                                <th id="pa_cio_governance_board_link">
                                    <a class="info-icon" href="<?php echo site_url('docs') . '#pa_cio_governance_board_link' ?>">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                    </a>
                                    Link to CIO Governance Board directory
                                </th>
                                <td>
                                    <a name="pa_cio_governance_board_link" class="anchor-point"></a>
                                    <a href="<?php echo $office_campaign->governanceboard_status->tracker_fields->pa_cio_governance_board_link;?>">
                                        <?php echo $office_campaign->governanceboard_status->tracker_fields->pa_cio_governance_board_link;?>
                                    </a>
                                </td>
                            </tr>
                        <?php endif; ?>

                    </table>
                </div>
            <?php endif; ?>

            <?php if ($valid_json == true && !empty($governance_board)): ?>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        Governance Boards
                        <a class="info-icon" href="<?php echo site_url('docs') . '#governanceboard_excerpts' ?>">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </a>
                    </div>
                    <div style="padding : 1em;">
                        <?php
                        $sections = array("1.2.4" => "edi_schedule_delivered",
                            "1.2.5" => "schedule",
                            "1.2.6" => "pe_feedback_specified",
                            "1.2.7" => "ps_publication_process");

                        if (!empty($governance_board->generated)) {
                            if ($published_date = strtotime($governance_board->generated)) {
                                $published_date = date("l, d-M-Y H:i:s T", $published_date);
                                echo '<h2><span style="color:#666">Date specified: </span>' . "$published_date</h2>";
                            }
                        }

                        if (!empty($office_campaign->governanceboard_status->filetime) && $office_campaign->governanceboard_status->filetime > 0) {
                            echo 'Date of governanceboard.json file: ' . date("l, d-M-Y H:i:s T", $office_campaign->governanceboard_status->filetime);
                        }

                        ?>

                        <?php
                        if (!empty($governance_board[0]->boards)) {
                            echo '<table class="table table-striped table-hover" style="border-bottom : 3px solid #ccc">';
                            echo "<tr>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Bureau Code</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Bureau Name</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Governance Board Name</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Federal Program Inventory Code</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>Federal Program Inventory Name</th>";
                            echo "<th class='col-sm-2 col-md-2 col-lg-2'>CIO Involvement Description</th>";
                            echo "</tr>";
                            foreach ($governance_board[0]->boards as $board) {
                                echo "<tr>";
                                echo "<td class='col-sm-2 col-md-2 col-lg-2'>" . $board->bureauCode . "</td>";
                                echo "<td class='col-sm-2 col-md-2 col-lg-2'>" . (isset($board->bureauName) ? $board->bureauName : "Agency-wide")  . "</td>";
                                echo "<td class='col-sm-2 col-md-6 col-lg-2'>" . $board->governanceBoardName . "</td>";
                                echo "<td class='col-sm-2 col-md-2 col-lg-2'>" . $board->programCodeFPI . "</td>";
                                echo "<td class='col-sm-2 col-md-2 col-lg-2'>" . (isset($board->programNameFPI) ? $board>programNameFPI : "") . "</td>";
                                echo "<td class='col-sm-6 col-md-6 col-lg-6'>" . (isset($board->cioInvolvementDescription) ? $board->cioInvolvementDescription : "") . "</td>";
                                echo "</tr>\n";
                            }
                            echo "</table>\n";
                        }

                        ?>

                    </div>
                </div>

            <?php endif; ?>

          <?php include "recommendation_detail_status.php" ?>
