<?php

$dgs_agencies = array(

	'generated' =>  date( 'Y-m-d H:i:s' ),
	'api_version' => '1.0.1',
	'agencies' => array(
		new DGS_Agency( 'Administration for Children and Families', 'ACF', 'http://www.acf.hhs.gov/' ),
		new DGS_Agency( 'Administration on Aging', 'AOA', 'http://www.aoa.gov/' ),
		new DGS_Agency( 'Administrative Conference of the United States', 'ACUS', 'http://www.acus.gov' ),
		new DGS_Agency( 'Administrative Office of the U.S. Courts', 'USC', 'http://www.uscourts.gov' ),
		new DGS_Agency( 'Advisory Council on Historic Preservation', 'ACHP', 'http://www.achp.gov' ),
		new DGS_Agency( 'African Development Foundation', 'ADF', 'http://www.adf.gov' ),
		new DGS_Agency( 'Agency for Healthcare Research and Quality', 'AHRQ', 'http://www.ahrq.gov/' ),
		new DGS_Agency( 'Agricultural Marketing Service', 'AMS', 'http://www.ams.usda.gov' ),
		new DGS_Agency( 'Agricultural Research Service', 'ARS', 'http://www.ars.usda.gov' ),
		new DGS_Agency( 'Alcohol and Tobacco Tax and Trade Bureau', 'TTB', 'http://www.ttb.gov/' ),
		new DGS_Agency( 'National Railroad Passenger Corporation', 'AMTRAK', 'http://www.amtrak.com' ),
		new DGS_Agency( 'Animal and Plant Health Inspection Service', 'APHIS', 'http://www.aphis.usda.gov/' ),
		new DGS_Agency( 'Architect of the Capitol', 'AOC', 'http://www.aoc.gov' ),
		new DGS_Agency( 'Broadcasting Board of Governors, International Broadcasting Bureau', 'BBG', 'http://www.bbg.gov' ),
		new DGS_Agency( 'Bureau of Alcohol, Tobacco, Firearms and Explosives', 'ATF', 'http://www.atf.gov/' ),
		new DGS_Agency( 'Bureau of Economic Analysis', 'BEA', 'http://www.bea.gov/' ),
		new DGS_Agency( 'Bureau of Engraving and Printing', 'BEP', 'http://www.moneyfactory.gov/' ),
		new DGS_Agency( 'Bureau of Indian Affairs', 'BIA', 'http://www.bia.gov/' ),
		new DGS_Agency( 'Bureau of Industry and Security', 'BIS', 'http://www.bis.doc.gov/' ),
		new DGS_Agency( 'Bureau of International Labor Affairs', 'BILA', 'http://www.dol.gov/ilab/' ),
		new DGS_Agency( 'Bureau of Labor Statistics', 'BLS', 'http://www.bls.gov/' ),
		new DGS_Agency( 'Bureau of Land Management', 'BLM', 'http://www.blm.gov' ),
		new DGS_Agency( 'Bureau of Ocean Energy Management', 'BOEM', 'http://www.boem.gov/' ),
		new DGS_Agency( 'Bureau of Reclamation', 'USBR', 'http://www.usbr.gov/' ),
		new DGS_Agency( 'Bureau of Safety and Environmental Enforcement', 'BSEE', 'http://www.bsee.gov/' ),
		new DGS_Agency( 'Bureau of the Census', 'CENSUS', 'http://www.census.gov/' ),
		new DGS_Agency( 'Bureau of the Public Debt', 'BOPD', 'http://www.publicdebt.treas.gov/' ),
		new DGS_Agency( 'Bureau of Transportation Statistics', 'BTS', 'http://www.bts.gov/' ),
		new DGS_Agency( 'Center for Faith-Based and Neighborhood Partnerships', 'CFBNP', 'http://www.dol.gov/cfbnp/' ),
		new DGS_Agency( 'Center for Nutrition Policy and Promotion', 'CNPP', 'http://www.cnpp.usda.gov' ),
		new DGS_Agency( 'Centers for Disease Control and Prevention', 'CDC', 'http://www.cdc.gov/' ),
		new DGS_Agency( 'Centers for Medicare and Medicaid Services', 'CMS', 'http://www.cms.gov/' ),
		new DGS_Agency( 'Central Intelligence Agency', 'CIA', 'http://www.cia.gov' ),
		new DGS_Agency( 'Commission on Civil Rights', 'USCCR', 'http://www.usccr.gov' ),
		new DGS_Agency( 'Commodity Futures Trading Commission', 'CFTC', 'http://www.cftc.gov' ),
		new DGS_Agency( 'Community Development Financial Institutions Fund', 'CDFIF', 'http://www.cdfifund.gov/' ),
		new DGS_Agency( 'Congressional Budget Office', 'CBO', 'http://www.cbo.gov' ),
		new DGS_Agency( 'Consumer Product Safety Commission', 'CPSC', 'http://www.cpsc.gov' ),
		new DGS_Agency( 'Corporation for National and Community Service', 'CNCS', 'http://www.nationalservice.gov' ),
		new DGS_Agency( 'Corporation for Public Broadcasting', 'CPB', 'http://www.cpb.org/' ),
		new DGS_Agency( 'Court Services and Offender Supervision Agency for the District of Columbia', 'CSOSA', 'http://www.csosa.gov' ),
		new DGS_Agency( 'Defense Advanced Research Projects Agency', 'DARPA', 'http://www.darpa.mil/' ),
		new DGS_Agency( 'Defense Commissary Agency', 'DCA', 'http://www.commissaries.com/' ),
		new DGS_Agency( 'Defense Contract Audit Agency', 'DCAA', 'http://www.dcaa.mil/' ),
		new DGS_Agency( 'Defense Contract Management Agency', 'DCMA', 'http://www.dcma.mil/' ),
		new DGS_Agency( 'Defense Finance and Accounting Service', 'DFAS', 'http://www.dfas.mil/' ),
		new DGS_Agency( 'Defense Human Resources Activity', 'DHRA', 'http://www.dhra.mil/' ),
		new DGS_Agency( 'Defense Information Systems Agency', 'DISA', 'http://www.disa.mil/' ),
		new DGS_Agency( 'Defense Intelligence Agency', 'DIA', 'http://www.dia.mil/' ),
		new DGS_Agency( 'Defense Logistics Agency', 'DLA', 'http://www.dla.mil' ),
		new DGS_Agency( 'Defense Nuclear Facilities Safety Board', 'DNFSB', 'http://www.dnfsb.gov' ),
		new DGS_Agency( 'Defense Prisoner of War/Missing Personnel Office', 'DPMO', 'http://www.dtic.mil/dpmo/' ),
		new DGS_Agency( 'Defense Security Cooperation Agency', 'DSCA', 'http://www.dsca.mil/' ),
		new DGS_Agency( 'Defense Security Service', 'DSS', 'http://www.dss.mil/' ),
		new DGS_Agency( 'Defense Technical Information Center', 'DTIC', 'http://www.dtic.mil/' ),
		new DGS_Agency( 'Defense Threat Reduction Agency', 'DTRA', 'http://www.dtra.mil' ),
		new DGS_Agency( 'Department of Agriculture', 'USDA', 'http://www.usda.gov' ),
		new DGS_Agency( 'Department of Commerce', 'DOC', 'http://www.commerce.gov' ),
		new DGS_Agency( 'Department of Defense', 'DOD', 'http://www.defense.gov' ),
		new DGS_Agency( 'Department of Defense Education Activity', 'DODEA', 'http://www.dodea.edu/' ),
		new DGS_Agency( 'Department of Education', 'ED', 'http://www.ed.gov' ),
		new DGS_Agency( 'Department of Energy', 'DOE', 'http://www.energy.gov' ),
		new DGS_Agency( 'Department of Health and Human Services', 'HHS', 'http://www.hhs.gov' ),
		new DGS_Agency( 'Department of Homeland Security', 'DHS', 'http://www.dhs.gov' ),
		new DGS_Agency( 'Department of Housing and Urban Development', 'HUD', 'http://www.hud.gov' ),
		new DGS_Agency( 'Department of Justice', 'DOJ', 'http://www.justice.gov' ),
		new DGS_Agency( 'Department of Labor', 'DOL', 'http://www.dol.gov' ),
		new DGS_Agency( 'Department of State', 'DOS', 'http://www.state.gov' ),
		new DGS_Agency( 'Department of the Air Force', 'AF', 'http://www.af.mil/' ),
		new DGS_Agency( 'Department of the Army', 'ARMY', 'http://www.army.mil/' ),
		new DGS_Agency( 'Department of the Interior', 'DOI', 'http://www.doi.gov' ),
		new DGS_Agency( 'Department of the Navy', 'NAVY', 'http://www.navy.mil/' ),
		new DGS_Agency( 'Department of the Treasury', 'TREAS', 'http://www.treasury.gov' ),
		new DGS_Agency( 'Department of Transportation', 'DOT', 'http://www.dot.gov' ),
		new DGS_Agency( 'Department of Veterans Affairs', 'VA', 'http://www.va.gov' ),
		new DGS_Agency( 'Drug Enforcement Administration', 'DEA', 'http://www.justice.gov/dea/' ),
		new DGS_Agency( 'Economic Development Administration', 'EDA', 'http://www.eda.gov/' ),
		new DGS_Agency( 'Economic Research Service', 'ERS', 'http://www.ers.usda.gov/' ),
		new DGS_Agency( 'Economics and Statistics Administration', 'ESA', 'http://www.esa.doc.gov/' ),
		new DGS_Agency( 'Election Assistance Commission', 'EAC', 'http://www.eac.gov' ),
		new DGS_Agency( 'Employee Benefits Security Administration', 'EBSA', 'http://www.dol.gov/ebsa/' ),
		new DGS_Agency( 'Employment and Training Administration', 'DOLETA', 'http://www.doleta.gov/' ),
		new DGS_Agency( 'Environmental Protection Agency', 'EPA', 'http://www.epa.gov' ),
		new DGS_Agency( 'Equal Employment Opportunity Commission', 'EEOC', 'http://www.eeoc.gov' ),
		new DGS_Agency( 'Executive Office of the President', 'EOP', 'http://www.whitehouse.gov' ),
		new DGS_Agency( 'Export-Import Bank of the United States', 'EXIM', 'http://www.exim.gov' ),
		new DGS_Agency( 'Farm Credit Administration', 'FCA', 'http://www.fca.gov' ),
		new DGS_Agency( 'Farm Service Agency', 'FSA', 'http://www.fsa.usda.gov' ),
		new DGS_Agency( 'Federal Aviation Administration', 'FAA', 'http://www.faa.gov/' ),
		new DGS_Agency( 'Federal Bureau of Investigation', 'FBI', 'http://www.fbi.gov/' ),
		new DGS_Agency( 'Federal Bureau of Prisons', 'BOP', 'http://www.bop.gov/' ),
		new DGS_Agency( 'Federal Communications Commission', 'FCC', 'http://www.fcc.gov' ),
		new DGS_Agency( 'Federal Consulting Group', 'FCG', 'http://www.fcg.gov/' ),
		new DGS_Agency( 'Federal Deposit Insurance Corporation', 'FDIC', 'http://www.fdic.gov' ),
		new DGS_Agency( 'Federal Election Commission', 'FEC', 'http://www.fec.gov' ),
		new DGS_Agency( 'Federal Emergency Management Agency', 'FEMA', 'http://www.fema.gov/' ),
		new DGS_Agency( 'Federal Energy Regulatory Commission', 'FERC', 'http://www.ferc.gov' ),
		new DGS_Agency( 'Federal Highway Administration', 'FHWA', 'http://www.fhwa.dot.gov/' ),
		new DGS_Agency( 'Federal Housing Administration', 'FHA', 'http://www.fha.gov/' ),
		new DGS_Agency( 'Federal Housing Finance Agency', 'FHFA', 'http://www.fhfa.gov/' ),
		new DGS_Agency( 'Federal Housing Finance Board', 'FHFB', 'http://www.fhfa.gov' ),
		new DGS_Agency( 'Federal Judicial Center', 'FJC', 'http://www.fjc.gov' ),
		new DGS_Agency( 'Federal Labor Relations Authority', 'FLRA', 'http://www.flra.gov' ),
		new DGS_Agency( 'Federal Law Enforcement Training Center', 'FLETC', 'http://www.fletc.gov/' ),
		new DGS_Agency( 'Federal Maritime Commission', 'FMC', 'http://www.fmc.gov' ),
		new DGS_Agency( 'Federal Mediation and Conciliation Service', 'FMCS', 'http://www.fmcs.gov' ),
		new DGS_Agency( 'Federal Mine Safety and Health Review Commission', 'FMSHRC', 'http://www.fmshrc.gov' ),
		new DGS_Agency( 'Federal Motor Carrier Safety Administration', 'FMCSA', 'http://www.fmcsa.dot.gov/' ),
		new DGS_Agency( 'Federal Railroad Administration', 'FRA', 'http://www.fra.dot.gov/' ),
		new DGS_Agency( 'Federal Reserve System', 'FRS', 'http://www.federalreserve.gov' ),
		new DGS_Agency( 'Federal Retirement Thrift Investment Board', 'FRTIB', 'http://www.frtib.gov' ),
		new DGS_Agency( 'Federal Student Aid', 'FAFSA', 'http://www.fafsa.ed.gov/' ),
		new DGS_Agency( 'Federal Trade Commission', 'FTC', 'http://www.ftc.gov' ),
		new DGS_Agency( 'Federal Transit Administration', 'FTA', 'http://www.fta.dot.gov/' ),
		new DGS_Agency( 'Financial Crimes Enforcement Network', 'FINCEN', 'http://www.fincen.gov/' ),
		new DGS_Agency( 'Financial Management Service', 'FMS', 'http://www.fms.treas.gov' ),
		new DGS_Agency( 'Fish and Wildlife Service', 'FWS', 'http://www.fws.gov/' ),
		new DGS_Agency( 'Food and Drug Administration', 'FDA', 'http://www.fda.gov/' ),
		new DGS_Agency( 'Food and Nutrition Service', 'FNS', 'http://www.fns.usda.gov/' ),
		new DGS_Agency( 'Food Safety and Inspection Service', 'FSIS', 'http://www.fsis.usda.gov/' ),
		new DGS_Agency( 'Foreign Agricultural Service', 'FAS', 'http://www.fas.usda.gov/' ),
		new DGS_Agency( 'Forest Service', 'FS', 'http://www.fs.fed.us/' ),
		new DGS_Agency( 'General Services Administration', 'GSA', 'http://www.gsa.gov' ),
		new DGS_Agency( 'Government Accountability Office', 'GAO', 'http://www.gao.gov' ),
		new DGS_Agency( 'Government Printing Office', 'GPO', 'http://www.gpo.gov' ),
		new DGS_Agency( 'Grain Inspection, Packers and Stockyards Administration', 'GIPSA', 'http://www.gipsa.usda.gov/' ),
		new DGS_Agency( 'Health Resources and Services Administration', 'HRSA', 'http://www.hrsa.gov' ),
		new DGS_Agency( 'House of Representatives', 'HOR', 'http://www.house.gov' ),
		new DGS_Agency( 'Indian Health Service', 'IHS', 'http://www.ihs.gov/' ),
		new DGS_Agency( 'Information Sharing Environment', 'ISE', 'http://www.ise.gov' ),
		new DGS_Agency( 'Institute of Education Sciences', 'IES', 'http://ies.ed.gov/' ),
		new DGS_Agency( 'Institute of Museum and Library Services', 'IMLS', 'http://www.imls.gov' ),
		new DGS_Agency( 'Inter-American Foundation', 'IAF', 'http://www.iaf.gov' ),
		new DGS_Agency( 'Internal Revenue Service', 'IRS', 'http://www.irs.gov' ),
		new DGS_Agency( 'International Trade Administration', 'TRADE', 'http://www.trade.gov/' ),
		new DGS_Agency( 'Job Corps', 'JC', 'http://www.jobcorps.gov' ),
		new DGS_Agency( 'Joint Chief of Staff', 'JCS', 'http://www.jcs.mil/' ),
		new DGS_Agency( 'Judicial Panel on Multidistrict Litigation', 'JPML', 'http://www.jpml.uscourts.gov' ),
		new DGS_Agency( 'Library of Congress', 'LOC', 'http://www.libraryofcongress.gov' ),
		new DGS_Agency( 'Maritime Administration', 'MARAD', 'http://www.marad.dot.gov/' ),
		new DGS_Agency( 'Merit Systems Protection Board', 'MSPB', 'http://www.mspb.gov' ),
		new DGS_Agency( 'Millennium Challenge Corporation', 'MCC', 'http://www.mcc.gov' ),
		new DGS_Agency( 'Mine Safety and Health Administration', 'MSHA', 'http://www.msha.gov/' ),
		new DGS_Agency( 'Minority Business Development Agency', 'MBDA', 'http://www.mbda.gov/' ),
		new DGS_Agency( 'Missile Defense Agency', 'MDA', 'http://www.mda.mil/' ),
		new DGS_Agency( 'National Aeronautics and Space Administration', 'NASA', 'http://www.nasa.gov' ),
		new DGS_Agency( 'National Agricultural Statistics Service', 'NASS', 'http://www.nass.usda.gov/' ),
		new DGS_Agency( 'National Archives and Records Administration', 'NARA', 'http://www.archives.gov' ),
		new DGS_Agency( 'National Capital Planning Commission', 'NCPC', 'http://www.ncpc.gov' ),
		new DGS_Agency( 'National Cemetery Administration', 'CEMVA', 'http://www.cem.va.gov/' ),
		new DGS_Agency( 'National Center for Education Statistics', 'NCES', 'http://nces.ed.gov/' ),
		new DGS_Agency( 'National Council on Disability', 'NCD', 'http://www.ncd.gov' ),
		new DGS_Agency( 'National Credit Union Administration', 'NCUA', 'http://www.ncua.gov' ),
		new DGS_Agency( 'National Endowment for the Arts', 'NEA', 'http://www.nea.gov' ),
		new DGS_Agency( 'National Endowment for the Humanities', 'NEH', 'http://www.neh.gov' ),
		new DGS_Agency( 'National Geospatial-Intelligence Agency', 'NGA', 'http://www.nga.mil/' ),
		new DGS_Agency( 'National Guard Bureau', 'NGB', 'http://www.nationalguard.mil/' ),
		new DGS_Agency( 'National Highway Traffic Safety Administration', 'NHTSA', 'http://www.nhtsa.gov/' ),
		new DGS_Agency( 'National Institute of Food and Agriculture', 'CSREES', 'http://www.csrees.usda.gov/' ),
		new DGS_Agency( 'National Institute of Standards and Technology', 'NIST', 'http://www.nist.gov' ),
		new DGS_Agency( 'National Institutes of Health', 'NIH', 'http://www.nih.gov/' ),
		new DGS_Agency( 'National Labor Relations Board', 'NLRB', 'http://www.nlrb.gov' ),
		new DGS_Agency( 'National Mediation Board', 'NMB', 'http://www.nmb.gov' ),
		new DGS_Agency( 'National Nuclear Security Administration', 'NNSA', 'http://nnsa.energy.gov/' ),
		new DGS_Agency( 'National Oceanic and Atmospheric Administration', 'NOAA', 'http://www.noaa.gov/' ),
		new DGS_Agency( 'National Park Service', 'NPS', 'http://www.nps.gov' ),
		new DGS_Agency( 'National Reconnaissance Office', 'NRO', 'http://www.nro.gov/' ),
		new DGS_Agency( 'National Science Foundation', 'NSF', 'http://www.nsf.gov' ),
		new DGS_Agency( 'National Security Agency', 'NSA', 'http://www.nsa.gov/' ),
		new DGS_Agency( 'National Telecommunications and Information Administration', 'NTIA', 'http://www.ntia.doc.gov/' ),
		new DGS_Agency( 'National Transportation Safety Board', 'NTSB', 'http://www.ntsb.gov' ),
		new DGS_Agency( 'Natural Resources Conservation Service', 'NRCS', 'http://www.nrcs.usda.gov' ),
		new DGS_Agency( 'Naval Criminal Investigative Service', 'NCIS', 'http://www.ncis.navy.mil' ),
		new DGS_Agency( 'Nuclear Regulatory Commission', 'NRC', 'http://www.nrc.gov' ),
		new DGS_Agency( 'Occupational Safety and Health Administration', 'OSHA', 'http://www.osha.gov/' ),
		new DGS_Agency( 'Occupational Safety and Health Review Commission', 'OSHRC', 'http://www.oshrc.gov' ),
		new DGS_Agency( 'Office for Civil Rights', 'OCR', 'http://www.ed.gov/ocr' ),
		new DGS_Agency( 'Office of Compliance', 'OOC', 'http://www.compliance.gov' ),
		new DGS_Agency( 'Office of Economic Adjustment', 'OEA', 'http://www.oea.gov/' ),
		new DGS_Agency( 'Office of Elementary and Secondary Education', 'EOSE', 'http://www.ed.gov/oese' ),
		new DGS_Agency( 'Office of Financial Stability', 'OFS', 'http://www.financialstability.gov' ),
		new DGS_Agency( 'Office of Government Ethics', 'USOGE', 'http://www.usoge.gov' ),
		new DGS_Agency( 'Office of Insular Affairs', 'OIA', 'http://www.doi.gov/oia/' ),
		new DGS_Agency( 'Office of Personnel Management', 'OPM', 'http://www.opm.gov' ),
		new DGS_Agency( 'Office of Postsecondary Education', 'OPE', 'http://www.ed.gov/ope' ),
		new DGS_Agency( 'Office of Special Counsel', 'OSC', 'http://www.osc.gov' ),
		new DGS_Agency( 'Office of Special Education and Rehabilitative Services', 'OSERS', 'http://www.ed.gov/osers' ),
		new DGS_Agency( 'Office of Surface Mining', 'OSMRE', 'http://www.osmre.gov/' ),
		new DGS_Agency( 'Office of the Comptroller of the Currency', 'OCC', 'http://www.occ.treas.gov/' ),
		new DGS_Agency( 'Office of the Director of National Intelligence', 'DNI', 'http://www.dni.gov' ),
		new DGS_Agency( 'Office of the National Counterintelligence Executive', 'NCIX', 'http://www.ncix.gov' ),
		new DGS_Agency( 'Office of Vocational and Adult Education', 'OVAE', 'http://www.ed.gov/ovae' ),
		new DGS_Agency( 'Overseas Private Investment Corporation', 'OPIC', 'http://www.opic.gov' ),
		new DGS_Agency( 'Panama Canal Authority', 'ACP', 'http://www.pancanal.com' ),
		new DGS_Agency( 'Patent and Trademark Office', 'PTO', 'http://www.uspto.gov/' ),
		new DGS_Agency( 'Peace Corps', 'PEACE', 'http://www.peacecorps.gov' ),
		new DGS_Agency( 'Pension Benefit Guaranty Corporation', 'PBGC', 'http://www.pbgc.gov' ),
		new DGS_Agency( 'Pentagon Force Protection Agency', 'PFPA', 'http://www.pfpa.mil/' ),
		new DGS_Agency( 'Pipeline and Hazardous Materials Safety Administration', 'PHMSA', 'http://www.phmsa.dot.gov/' ),
		new DGS_Agency( 'Postal Regulatory Commission', 'PRC', 'http://www.prc.gov' ),
		new DGS_Agency( 'Railroad Retirement Board', 'RRB', 'http://www.rrb.gov' ),
		new DGS_Agency( 'Research and Innovative Technology Administration', 'RITA', 'http://www.rita.dot.gov/' ),
		new DGS_Agency( 'Risk Management Agency', 'RMA', 'http://www.rma.usda.gov/' ),
		new DGS_Agency( 'Rural Utilities Service', 'RURDEV', 'http://www.rurdev.usda.gov' ),
		new DGS_Agency( 'Saint Lawrence Seaway Development Corporation', 'SEAWAY', 'http://www.seaway.dot.gov/' ),
		new DGS_Agency( 'Securities and Exchange Commission', 'SEC', 'http://www.sec.gov' ),
		new DGS_Agency( 'Securities Investor Protection Corporation', 'SIPC', 'http://www.sipc.org/' ),
		new DGS_Agency( 'Selective Service System', 'SSS', 'http://www.sss.gov' ),
		new DGS_Agency( 'Small Business Administration', 'SBA', 'http://www.sba.gov' ),
		new DGS_Agency( 'Social Security Administration', 'SSA', 'http://www.ssa.gov' ),
		new DGS_Agency( 'Substance Abuse and Mental Health Services Administration', 'SAMHSA', 'http://www.samhsa.gov/' ),
		new DGS_Agency( 'Supreme Court', 'SCOTUS', 'http://www.supremecourt.gov' ),
		new DGS_Agency( 'Surface Transportation Board', 'STB', 'http://www.stb.dot.gov' ),
		new DGS_Agency( 'Tennessee Valley Authority', 'TVA', 'http://www.tva.gov' ),
		new DGS_Agency( 'Transportation Security Administration', 'TSA', 'http://www.tsa.gov/' ),
		new DGS_Agency( 'TRICARE Management Activity', 'TMA', 'http://www.tricare.mil/tma/' ),
		new DGS_Agency( 'U.S. Court of Appeals', 'CAFC', 'http://www.cafc.uscourts.gov' ),
		new DGS_Agency( 'U.S. Court of Appeals for the Armed Forces', 'ARMFOR', 'http://www.armfor.uscourts.gov' ),
		new DGS_Agency( 'U.S. Court of Appeals for Veterans Claims', 'CAVC', 'http://www.uscourts.cavc.gov' ),
		new DGS_Agency( 'U.S. Court of Federal Claims', 'USCFC', 'http://www.uscfc.uscourts.gov' ),
		new DGS_Agency( 'U.S. Court of International Trade', 'USCIT', 'http://www.cit.uscourts.gov' ),
		new DGS_Agency( 'U.S. Energy Information Administration', 'EIA', 'http://www.eia.gov' ),
		new DGS_Agency( 'U.S. Senate', 'SENATE', 'http://www.senate.gov' ),
		new DGS_Agency( 'U.S. Sentencing Commission', 'USSC', 'http://www.ussc.gov' ),
		new DGS_Agency( 'U.S. Tax Court', 'TAX', 'http://www.ustaxcourt.gov' ),
		new DGS_Agency( 'U.S. Trade and Development Agency', 'USTDA', 'http://www.ustda.gov' ),
		new DGS_Agency( 'United States Agency for International Development', 'USAID', 'http://www.usaid.gov' ),
		new DGS_Agency( 'United States Botanic Garden', 'USBG', 'http://www.usbg.gov' ),
		new DGS_Agency( 'United States Citizenship and Immigration Services', 'USCIS', 'http://www.uscis.gov/portal/site/uscis' ),
		new DGS_Agency( 'United States Coast Guard ', 'USCG', 'http://www.uscg.mil/' ),
		new DGS_Agency( 'United States Customs and Border Protection', 'CBP', 'http://www.cbp.gov/' ),
		new DGS_Agency( 'United States Geological Survey', 'USGS', 'http://www.usgs.gov/' ),
		new DGS_Agency( 'United States Immigration and Customs Enforcement', 'ICE', 'http://www.ice.gov/' ),
		new DGS_Agency( 'United States International Trade Commission', 'USITC', 'http://www.usitc.gov' ),
		new DGS_Agency( 'United States Marshals', 'MARSHAL', 'http://www.usmarshals.gov/' ),
		new DGS_Agency( 'United States Mint', 'MINT', 'http://www.usmint.gov/' ),
		new DGS_Agency( 'United States Postal Service', 'USPS', 'http://www.usps.com' ),
		new DGS_Agency( 'United States Secret Service', 'USSS', 'http://www.secretservice.gov/' ),
		new DGS_Agency( 'Veterans Benefits Administration', 'VBA', 'http://www.vba.va.gov/' ),
		new DGS_Agency( 'Veterans Health Administration', 'VHA', 'http://www.va.gov/health' ),
		new DGS_Agency( 'Veterans\' Employment and Training Service', 'VETS', 'http://www.dol.gov/vets/' ),
		new DGS_Agency( 'Wage and Hour Division', 'WHD', 'http://www.dol.gov/whd/' ),
		new DGS_Agency( 'Washington Headquarters Services', 'WHS', 'http://www.whs.mil/' ),
		new DGS_Agency( 'Women\'s Bureau', 'WB', 'http://www.dol.gov/wb/' ),
	),

);
