DROP TABLE IF EXISTS `offices`;

CREATE TABLE `offices` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `url_slug` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(256) CHARACTER SET latin1 DEFAULT NULL,
  `abbreviation` text CHARACTER SET latin1,
  `url` text CHARACTER SET latin1,
  `notes` text CHARACTER SET latin1,
  `parent_office_id` int(10) DEFAULT NULL,
  `no_parent` varchar(256) CHARACTER SET latin1 NOT NULL,
  `reporting_authority_type` varchar(256) CHARACTER SET latin1 NOT NULL,
  `cfo_act_agency` varchar(256) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `offices` (`id`, `url_slug`, `name`, `abbreviation`, `url`, `notes`, `parent_office_id`, `no_parent`, `reporting_authority_type`, `cfo_act_agency`)
VALUES
	(47994,NULL,'Administration for Children and Families','ACF','http://www.acf.hhs.gov/',NULL,49021,'false','executive','false'),
	(47995,NULL,'Administration on Aging','AoA','http://www.aoa.gov/',NULL,91836,'false','executive','false'),
	(47996,NULL,'AIDS.gov',NULL,'http://www.aids.gov/',NULL,49021,'false','executive','false'),
	(48005,NULL,'Bureau of the Census',NULL,'http://www.census.gov',NULL,52668,'false','executive','false'),
	(48006,NULL,'Bureau of the Public Debt',NULL,'http://www.publicdebt.treas.gov/',NULL,49034,'false','executive','false'),
	(48007,NULL,'CDC National STD Hotline',NULL,'http://www.cdc.gov/std',NULL,49021,'false','executive','false'),
	(48012,NULL,'Center for Nutrition Policy and Promotion','CNPP','http://www.cnpp.usda.gov/',NULL,49015,'false','executive','false'),
	(48013,NULL,'Centers for Disease Control and Prevention','CDC','http://www.cdc.gov/',NULL,49021,'false','executive','false'),
	(48016,NULL,'Child Welfare Information Gateway',NULL,'http://www.childwelfare.gov',NULL,49021,'false','executive','false'),
	(48018,NULL,'Commission on Civil Rights',NULL,'http://www.usccr.gov',NULL,NULL,'true','independent','false'),
	(48020,NULL,'Consumer Center',NULL,'http://www.fcc.gov/cgb/',NULL,49041,'false','independent','false'),
	(48023,NULL,'Customer Contact Center',NULL,'http://www.pbgc.gov/',NULL,49052,'false','independent','false'),
	(48027,NULL,'Department of Veterans Affairs','VA','http://www.va.gov/',NULL,NULL,'true','executive','true'),
	(48028,NULL,'Eldercare Locator',NULL,'http://www.eldercare.gov/',NULL,49021,'false','executive','false'),
	(48029,NULL,'Employee Benefits Security Administration','EBSA','http://www.dol.gov/ebsa/',NULL,49028,'false','executive','false'),
	(48030,NULL,'Energy Efficiency and Renewable Energy','EERE','http://www.energysavers.gov/',NULL,49019,'false','executive','false'),
	(48031,NULL,'Energy Star Program',NULL,'http://www.energystar.gov',NULL,49039,'false','independent','false'),
	(48032,NULL,'Equal Employment Opportunity Commission','EEOC','http://www.eeoc.gov/',NULL,NULL,'true','independent','false'),
	(48033,NULL,'Federal Aviation Administration','FAA','http://www.faa.gov/',NULL,49035,'false','executive','false'),
	(48042,NULL,'Federal Emergency Management Agency','FEMA','http://www.fema.gov/',NULL,49022,'false','executive','false'),
	(48044,NULL,'Federal Housing Administration','FHA','http://portal.hud.gov/hudportal/HUD?src=/federal_housing_administration',NULL,49023,'false','executive','false'),
	(48048,NULL,'Federal Reserve Consumer Help',NULL,'http://www.federalreserveconsumerhelp.gov/',NULL,49046,'false','independent','false'),
	(48055,NULL,'FEMA Disaster Assistance',NULL,'http://www.fema.gov/assistance',NULL,49022,'false','executive','false'),
	(48057,NULL,'Fish and Wildlife Service','FWS','http://www.fws.gov/',NULL,49033,'false','executive','false'),
	(48058,NULL,'Food and Drug Administration','FDA','http://www.fda.gov/',NULL,49021,'false','executive','false'),
	(48059,NULL,'Food and Nutrition Service',NULL,'http://www.fns.usda.gov',NULL,49015,'false','executive','false'),
	(48061,NULL,'General Information Line',NULL,'http://www.usda.gov/wps/portal/usda/usdahome',NULL,49015,'false','executive','false'),
	(48062,NULL,'HHS-TIPS Fraud Hotline',NULL,'http://www.oig.hhs.gov',NULL,49021,'false','executive','false'),
	(48068,NULL,'Internal Revenue Service','IRS','http://www.irs.gov',NULL,49034,'false','executive','false'),
	(48069,NULL,'Job Corps',NULL,'http://www.jobcorps.gov',NULL,49028,'false','executive','false'),
	(48074,NULL,'National Cemetery Administration',NULL,'http://www.cem.va.gov/',NULL,48027,'false','executive','false'),
	(48075,NULL,'National Contact Center',NULL,'http://www.dol.gov/',NULL,49028,'false','executive','false'),
	(48076,NULL,'National Council on Disability','NCD','http://www.ncd.gov/',NULL,NULL,'true','independent','false'),
	(48078,NULL,'National Flood Insurance Program','NFIP','http://www.floodsmart.gov/',NULL,48042,'false','executive','false'),
	(48079,NULL,'National Health Information Center','NHIC','http://www.health.gov/nhic',NULL,49021,'false','executive','false'),
	(48081,NULL,'National Highway Traffic Safety Administration',NULL,'http://www.nhtsa.dot.gov/',NULL,49035,'false','executive','false'),
	(48082,NULL,'National Institute of Allergy and Infectious Diseases','NIAID','http://www.niaid.nih.gov',NULL,49021,'false','executive','false'),
	(48084,NULL,'National Institute of Food and Agriculture',NULL,'http://www.nifa.usda.gov',NULL,49015,'false','executive','false'),
	(48087,NULL,'National Institute of Mental Health','NIMH','http://www.nimh.nih.gov',NULL,48089,'false','executive','false'),
	(48089,NULL,'National Institutes of Health','NIH','http://www.nih.gov/',NULL,49021,'false','executive','false'),
	(48092,NULL,'National Passport Information Center','NPIC','http://travel.state.gov/content/passports/english/contact-us.html',NULL,92601,'false','executive','false'),
	(48094,NULL,'National Pesticide Information Center',NULL,'http://npic.orst.edu',NULL,49039,'false','independent','false'),
	(48096,NULL,'National Runaway Safeline','NRS','http://www.1800runaway.org',NULL,49021,'false','executive','false'),
	(48099,NULL,'National Service Center for Environmental Publications','NSCEP','http://www.epa.gov/nscep',NULL,49039,'false','independent','false'),
	(48101,NULL,'Occupational Safety and Health Administration','OSHA','http://www.osha.gov/',NULL,49028,'false','executive','false'),
	(48102,NULL,'Office for Civil Rights, Department of Education',NULL,'http://www.ed.gov/ocr',NULL,49018,'false','executive','false'),
	(48104,NULL,'Office of Child Support Enforcement','OCSE','http://www.acf.hhs.gov/programs/cse/',NULL,49021,'false','executive','false'),
	(48105,NULL,'Office of Disability Employment Policy',NULL,'http://www.dol.gov/odep',NULL,49028,'false','executive','false'),
	(48107,NULL,'Office of Fair Housing and Equal Opportunity',NULL,'http://www.hud.gov/offices/fheo/',NULL,49023,'false','executive','false'),
	(48109,NULL,'Office of Investor Education and Advocacy','OIEA','http://www.investor.gov/',NULL,49054,'false','independent','false'),
	(48112,NULL,'Office of Personnel Management','OPM','http://www.opm.gov/',NULL,NULL,'true','independent','true'),
	(48113,NULL,'Office of Postsecondary Education','OPE','http://www2.ed.gov/about/offices/list/ope/index.html',NULL,49018,'false','executive','false'),
	(48115,NULL,'Office of Public Inquiries',NULL,'http://www.socialsecurity.gov',NULL,49057,'false','independent','false'),
	(48121,NULL,'Office of Special Education and Rehabilitative Services','OSERS','http://www.ed.gov/about/offices/list/osers/index.html',NULL,49018,'false','executive','false'),
	(48126,NULL,'Office of the Comptroller of the Currency','OCC','http://www.occ.gov/',NULL,49034,'false','executive','false'),
	(48129,NULL,'Office of Vocational and Adult Education','OVAE','http://www2.ed.gov/about/offices/list/ovae/index.html',NULL,49018,'false','executive','false'),
	(48131,NULL,'American Citizens Services and Crisis Management',NULL,'http://travel.state.gov/content/passports/english/go.html',NULL,92601,'false','executive','false'),
	(48133,NULL,'Public Affairs',NULL,'http://energy.gov/public-services',NULL,49019,'false','executive','false'),
	(48139,NULL,'Small Business Administration','SBA','http://www.sba.gov/',NULL,NULL,'true','independent','true'),
	(48140,NULL,'Surplus Federal Property Sales',NULL,'http://www.gsaauctions.gov/',NULL,49048,'false','independent','false'),
	(48141,NULL,'The Education Publications Center','EDPUBS','http://www.edpubs.gov',NULL,49018,'false','executive','false'),
	(48143,NULL,'Transportation Security Administration','TSA','http://www.tsa.gov',NULL,49022,'false','executive','false'),
	(48146,NULL,'U.S. Commodity Futures Trading Commission','CFTC','http://www.cftc.gov',NULL,NULL,'true','independent','false'),
	(48148,NULL,'U.S. Trustee Program',NULL,'http://www.justice.gov/ust',NULL,52686,'false','executive','false'),
	(48150,NULL,'United States Mint',NULL,'http://www.usmint.gov',NULL,49034,'false','executive','false'),
	(48151,NULL,'U.S. Patent and Trademark Office',NULL,'http://www.uspto.gov/',NULL,52668,'false','executive','false'),
	(48154,NULL,'United States Postal Inspection Service',NULL,'http://postalinspectors.uspis.gov/',NULL,49061,'false','independent','false'),
	(48156,NULL,'Veterans Benefits Administration',NULL,'http://www.vba.va.gov/',NULL,48027,'false','executive','false'),
	(48158,NULL,'Veterans Employment and Training Service','VETS','http://www.dol.gov/vets/',NULL,49028,'false','executive','false'),
	(48159,NULL,'Veterans Health Administration','VHA','http://www.va.gov/health',NULL,NULL,'true','independent','false'),
	(48161,NULL,'Visa Services',NULL,'http://travel.state.gov/content/visas/english.html',NULL,92601,'false','executive','false'),
	(48165,NULL,'Wireless Telecommunications Bureau','WTB','http://wireless.fcc.gov/',NULL,49041,'false','independent','false'),
	(49013,NULL,'Consumer Product Safety Commission','CPSC','http://www.cpsc.gov/',NULL,NULL,'true','independent','false'),
	(49015,NULL,'Department of Agriculture','USDA','http://www.usda.gov/wps/portal/usda/usdahome',NULL,NULL,'true','executive','true'),
	(49018,NULL,'Department of Education','ED','http://www.ed.gov',NULL,NULL,'true','executive','true'),
	(49019,NULL,'Department of Energy','DOE','http://www.energy.gov/',NULL,NULL,'true','executive','true'),
	(49021,NULL,'Department of Health and Human Services','HHS','http://www.hhs.gov/',NULL,NULL,'true','executive','true'),
	(49022,NULL,'Department of Homeland Security','DHS','http://www.dhs.gov',NULL,NULL,'true','executive','true'),
	(49023,NULL,'Department of Housing and Urban Development','HUD','http://www.hud.gov',NULL,NULL,'true','executive','true'),
	(49028,NULL,'Department of Labor','DOL','http://www.dol.gov/',NULL,NULL,'true','executive','true'),
	(49030,NULL,'Department of State','DOS','http://www.state.gov',NULL,NULL,'true','executive','true'),
	(49033,NULL,'Department of the Interior','DOI','http://www.doi.gov/',NULL,NULL,'true','executive','true'),
	(49034,NULL,'Department of the Treasury',NULL,'http://www.treasury.gov/Pages/default.aspx',NULL,NULL,'true','executive','true'),
	(49035,NULL,'Department of Transportation','DOT','http://www.dot.gov/',NULL,NULL,'true','executive','true'),
	(49039,NULL,'Environmental Protection Agency','EPA','http://www.epa.gov/',NULL,NULL,'true','independent','true'),
	(49041,NULL,'Federal Communications Commission','FCC','http://www.fcc.gov/',NULL,NULL,'true','independent','false'),
	(49043,NULL,'Federal Deposit Insurance Corporation','FDIC','http://www.fdic.gov/',NULL,NULL,'true','independent','false'),
	(49046,NULL,'Federal Reserve System',NULL,'http://www.federalreserve.gov/',NULL,NULL,'true','independent','false'),
	(49047,NULL,'Federal Trade Commission','FTC','http://www.ftc.gov/',NULL,NULL,'true','independent','false'),
	(49048,NULL,'General Services Administration','GSA','http://www.gsa.gov/',NULL,NULL,'true','independent','true'),
	(49050,NULL,'National Credit Union Administration',NULL,'http://www.ncua.gov/',NULL,NULL,'true','independent','false'),
	(49052,NULL,'Pension Benefit Guaranty Corporation','PBGC','http://www.pbgc.gov/',NULL,NULL,'true','independent','false'),
	(49054,NULL,'Securities and Exchange Commission','SEC','http://www.sec.gov/',NULL,NULL,'true','independent','false'),
	(49057,NULL,'Social Security Administration','SSA','http://www.ssa.gov/',NULL,NULL,'true','independent','true'),
	(49061,NULL,'U.S. Postal Service','USPS','https://www.usps.com/',NULL,NULL,'true','independent','false'),
	(49064,NULL,'Administration for Native Americans',NULL,'http://www.acf.hhs.gov/programs/ana/',NULL,47994,'false','executive','false'),
	(49066,NULL,'Administration on Developmental Disabilities',NULL,'http://www.acf.hhs.gov/programs/add/',NULL,47994,'false','executive','false'),
	(49067,NULL,'Office of the Federal Register',NULL,'http://ofr.gov/',NULL,49483,'false','independent','false'),
	(49068,NULL,'Administrative Conference of the United States',NULL,'http://acus.gov/',NULL,NULL,'true','independent','false'),
	(49070,NULL,'Administrative Office of the U.S. Courts',NULL,'http://www.uscourts.gov/',NULL,NULL,'true','independent','false'),
	(49074,NULL,'Agency for Healthcare Research and Quality','AHRQ','http://www.ahrq.gov/',NULL,49021,'false','executive','false'),
	(49076,NULL,'Agency for Toxic Substances and Disease Registry',NULL,'http://www.atsdr.cdc.gov/',NULL,48013,'false','executive','false'),
	(49077,NULL,'Agricultural Marketing Service',NULL,'http://www.ams.usda.gov/',NULL,49450,'false','executive','false'),
	(49078,NULL,'Agricultural Research Service',NULL,'http://www.ars.usda.gov/',NULL,49015,'false','executive','false'),
	(49080,NULL,'U.S. Air Force',NULL,'http://www.af.mil/',NULL,49229,'false','executive','false'),
	(49081,NULL,'Bureau of Alcohol, Tobacco, Firearms, and Explosives',NULL,'http://www.atf.gov',NULL,52686,'false','executive','false'),
	(49082,NULL,'Alcohol and Tobacco Tax and Trade Bureau',NULL,'http://www.ttb.gov/',NULL,49034,'false','executive','false'),
	(49084,NULL,'National Railroad Passenger Corporation','AMTRAK','http://www.amtrak.com/',NULL,NULL,'true','independent','false'),
	(49085,NULL,'Animal and Plant Health Inspection Service',NULL,'http://www.aphis.usda.gov/',NULL,49450,'false','executive','false'),
	(49088,NULL,'Architect of the Capitol',NULL,'http://www.aoc.gov/',NULL,49664,'false','independent','false'),
	(49092,NULL,'U.S. Arctic Research Commission',NULL,'http://www.arctic.gov/',NULL,NULL,'true','independent','false'),
	(49093,NULL,'Armed Forces Retirement Home',NULL,'http://www.afrh.gov/',NULL,NULL,'true','independent','false'),
	(49095,NULL,'Arms Control and International Security',NULL,'http://www.state.gov/t/',NULL,49030,'false','executive','false'),
	(49096,NULL,'U.S. Army',NULL,'http://www.army.mil/',NULL,49229,'false','executive','false'),
	(49098,NULL,'U.S. Army Corps of Engineers',NULL,'http://www.usace.army.mil/',NULL,49096,'false','executive','false'),
	(49100,NULL,'Arthritis and Musculoskeletal Interagency Coordinating Committee',NULL,'http://www.niams.nih.gov/',NULL,48089,'false','executive','false'),
	(49101,NULL,'U.S. Fleet Forces Command',NULL,'http://www.cffc.navy.mil/',NULL,49229,'false','executive','false'),
	(49102,NULL,'Bankruptcy Courts',NULL,'http://www.uscourts.gov/bankruptcycourts.html',NULL,NULL,'true','independent','false'),
	(49105,NULL,'Barry M. Goldwater Scholarship and Excellence in Education Program',NULL,'http://www.act.org/goldwater/',NULL,NULL,'true','independent','false'),
	(49106,NULL,'Bonneville Power Administration',NULL,'http://www.bpa.gov/corporate/',NULL,49624,'false','executive','false'),
	(49108,NULL,'U.S. Botanic Garden',NULL,'http://www.usbg.gov/',NULL,49088,'false','independent','false'),
	(49109,NULL,'Broadcasting Board of Governors',NULL,'http://www.bbg.gov/',NULL,NULL,'true','independent','false'),
	(49113,NULL,'Consumer Financial Protection Bureau',NULL,'http://www.consumerfinance.gov',NULL,NULL,'true','independent','false'),
	(49115,NULL,'Bureau of Economic Analysis','BEA','http://www.bea.gov/',NULL,52668,'false','executive','false'),
	(49117,NULL,'Bureau of Indian Affairs',NULL,'http://www.bia.gov/',NULL,49033,'false','executive','false'),
	(49120,NULL,'Bureau of Industry and Security',NULL,'http://www.bis.doc.gov/',NULL,52668,'false','executive','false'),
	(49121,NULL,'Bureau of International Labor Affairs',NULL,'http://www.dol.gov/ilab/',NULL,49028,'false','executive','false'),
	(49124,NULL,'Bureau of Labor Statistics',NULL,'http://stats.bls.gov/',NULL,49028,'false','executive','false'),
	(49125,NULL,'Bureau of Land Management','BLM','http://www.blm.gov/wo/st/en.html',NULL,49033,'false','executive','false'),
	(49126,NULL,'Bureau of Prisons',NULL,'http://www.bop.gov/',NULL,52686,'false','executive','false'),
	(49128,NULL,'Bureau of Reclamation',NULL,'http://www.usbr.gov/',NULL,49033,'false','executive','false'),
	(49129,NULL,'Bureau of Transportation Statistics',NULL,'http://www.bts.gov/',NULL,49035,'false','executive','false'),
	(49134,NULL,'Centers for Medicare and Medicaid Services','CMS','http://www.cms.gov',NULL,49021,'false','executive','false'),
	(49135,NULL,'U.S. Central Command','CENTCOM','http://www.centcom.mil/',NULL,49726,'false','executive','false'),
	(49139,NULL,'Chief Acquisition Officers Council',NULL,'http://www.cao.gov',NULL,NULL,'true','independent','false'),
	(49141,NULL,'Chief Financial Officers Council',NULL,'http://www.cfo.gov',NULL,NULL,'true','independent','false'),
	(49143,NULL,'Chief Human Capital Officers Council',NULL,'http://www.chcoc.gov/',NULL,NULL,'true','independent','false'),
	(49145,NULL,'Chief Information Officers Council',NULL,'http://www.cio.gov/',NULL,NULL,'true','independent','false'),
	(49146,NULL,'Citizens\' Stamp Advisory Committee',NULL,'http://about.usps.com/who-we-are/leadership/stamp-advisory-committee.htm',NULL,NULL,'true','independent','false'),
	(49149,NULL,'U.S. Coast Guard',NULL,'http://www.uscg.mil/',NULL,49022,'false','executive','false'),
	(49153,NULL,'U.S. Commission on International Religious Freedom',NULL,'http://www.uscirf.gov/',NULL,NULL,'true','independent','false'),
	(49155,NULL,'Commission on Security and Cooperation in Europe','Helsinki Commission','http://www.csce.gov',NULL,NULL,'true','independent','false'),
	(49157,NULL,'U.S. AbilityOne Commission',NULL,'http://www.abilityone.gov',NULL,NULL,'true','independent','false'),
	(49159,NULL,'Committee for the Implementation of Textile Agreements',NULL,'http://otexa.ita.doc.gov/cita.htm',NULL,52668,'false','executive','false'),
	(49161,NULL,'Committee on Foreign Investment in the United States',NULL,'http://www.treasury.gov/about/organizational-structure/offices/International-Affairs/Pages/cfius-index.aspx',NULL,NULL,'true','independent','false'),
	(49162,NULL,'Community Oriented Policing Services','COPS','http://www.cops.usdoj.gov/',NULL,52686,'false','executive','false'),
	(49163,NULL,'Office of Community Planning and Development',NULL,'http://www.hud.gov/offices/cpd/index.cfm',NULL,49023,'false','executive','false'),
	(49166,NULL,'Computer Emergency Readiness Team','US CERT','http://www.us-cert.gov/',NULL,49022,'false','executive','false'),
	(49167,NULL,'Congressional Budget Office','CBO','http://www.cbo.gov/',NULL,49664,'false','independent','false'),
	(49169,NULL,'Congressional Research Service',NULL,'http://www.loc.gov/crsinfo/about/',NULL,52628,'false','independent','false'),
	(49174,NULL,'Coordinating Council on Juvenile Justice and Delinquency Prevention',NULL,'http://www.juvenilecouncil.gov/',NULL,NULL,'true','independent','false'),
	(49176,NULL,'Copyright Office',NULL,'http://www.copyright.gov/',NULL,52628,'false','independent','false'),
	(49180,NULL,'Council of Economic Advisers',NULL,'http://www.whitehouse.gov/cea/index.html',NULL,NULL,'true','executive','false'),
	(49181,NULL,'Council on Environmental Quality',NULL,'http://www.whitehouse.gov/administration/eop/ceq/',NULL,NULL,'true','executive','false'),
	(49182,NULL,'Court of Appeals for the Armed Forces',NULL,'http://www.armfor.uscourts.gov/index.html',NULL,NULL,'true','independent','false'),
	(49184,NULL,'Court of Appeals for the Federal Circuit',NULL,'http://www.cafc.uscourts.gov/',NULL,NULL,'true','independent','false'),
	(49186,NULL,'U.S. Court of Appeals for Veterans Claims',NULL,'http://www.uscourts.cavc.gov',NULL,NULL,'true','independent','false'),
	(49188,NULL,'Court of Federal Claims',NULL,'http://www.uscfc.uscourts.gov/',NULL,NULL,'true','independent','false'),
	(49189,NULL,'Court of International Trade',NULL,'http://www.cit.uscourts.gov/',NULL,NULL,'true','independent','false'),
	(49191,NULL,'Court Services and Offender Supervision Agency for the District of Columbia',NULL,'http://www.csosa.gov',NULL,NULL,'true','independent','false'),
	(49194,NULL,'Defense Acquisition University',NULL,'http://www.dau.mil/',NULL,49229,'false','executive','false'),
	(49195,NULL,'Defense Advanced Research Projects Agency','DARPA','http://www.darpa.mil/',NULL,49229,'false','executive','false'),
	(49197,NULL,'Defense Commissary Agency',NULL,'http://www.commissaries.com/',NULL,49229,'false','executive','false'),
	(49200,NULL,'Defense Contract Audit Agency','DCAA','http://www.dcaa.mil/',NULL,49229,'false','executive','false'),
	(49202,NULL,'Defense Contract Management Agency',NULL,'http://www.dcma.mil/',NULL,49229,'false','executive','false'),
	(49206,NULL,'Defense Field Activities',NULL,'http://www.defenselink.mil/pubs/almanac/',NULL,NULL,'true','independent','false'),
	(49209,NULL,'Defense Information Systems Agency','DISA','http://www.disa.mil/',NULL,49229,'false','executive','false'),
	(49211,NULL,'Defense Intelligence Agency','DIA','http://www.dia.mil',NULL,49229,'false','executive','false'),
	(49213,NULL,'Defense Legal Services Agency',NULL,'http://www.defenselink.mil/dodgc/',NULL,49229,'false','executive','false'),
	(49217,NULL,'Defense Security Cooperation Agency','DSCA','http://www.dsca.mil/',NULL,49229,'false','executive','false'),
	(49219,NULL,'Defense Security Service','DSS','http://www.dss.mil/',NULL,49229,'false','executive','false'),
	(49221,NULL,'Defense Technical Information Center',NULL,'http://www.dtic.mil',NULL,49229,'false','executive','false'),
	(49223,NULL,'Defense Threat Reduction Agency','DTRA','http://www.dtra.mil/',NULL,49229,'false','executive','false'),
	(49225,NULL,'Delaware River Basin Commission',NULL,'http://www.state.nj.us/drbc/drbc.htm',NULL,NULL,'true','independent','false'),
	(49227,NULL,'Denali Commission',NULL,'http://www.denali.gov/',NULL,NULL,'true','independent','false'),
	(49229,NULL,'Department of Defense',NULL,'http://www.defense.gov/',NULL,NULL,'true','executive','true'),
	(49235,NULL,'Domestic Policy Council',NULL,'http://www.whitehouse.gov/dpc/index.html',NULL,NULL,'true','executive','false'),
	(49237,NULL,'Economic, Business and Agricultural Affairs',NULL,'http://www.state.gov/e/',NULL,NULL,'true','independent','false'),
	(49238,NULL,'Economic Adjustment Office',NULL,'http://www.oea.gov',NULL,49229,'false','executive','false'),
	(49240,NULL,'Economic Development Administration','EDA','http://www.eda.gov/',NULL,52668,'false','executive','false'),
	(49242,NULL,'Economic Research Service',NULL,'http://www.ers.usda.gov/',NULL,49015,'false','executive','false'),
	(49243,NULL,'Economics and Statistics Administration',NULL,'http://www.esa.doc.gov/',NULL,52668,'false','executive','false'),
	(49250,NULL,'Endangered Species Program',NULL,'http://endangered.fws.gov/',NULL,48057,'false','executive','false'),
	(49255,NULL,'Energy Information Administration',NULL,'http://www.eia.doe.gov/',NULL,49019,'false','executive','false'),
	(49256,NULL,'English Language Acquisition Office',NULL,'http://www.ed.gov/oela',NULL,49018,'false','executive','false'),
	(49259,NULL,'Environmental Management','Energy Department','http://www.em.doe.gov/',NULL,49019,'false','executive','false'),
	(49261,NULL,'European Command',NULL,'http://www.eucom.mil',NULL,49726,'false','executive','false'),
	(49263,NULL,'Executive Office for Immigration Review',NULL,'http://www.usdoj.gov/eoir/',NULL,52686,'false','executive','false'),
	(49266,NULL,'Office of Elementary and Secondary Education','OESE','http://www.ed.gov/oese',NULL,49018,'false','executive','false'),
	(49267,NULL,'Fair Housing and Equal Opportunity','FHEO','http://www.hud.gov/offices/fheo/index.cfm',NULL,49023,'false','executive','false'),
	(49272,NULL,'Farm Service Agency',NULL,'http://www.fsa.usda.gov',NULL,49015,'false','executive','false'),
	(49275,NULL,'Federal Accounting Standards Advisory Board',NULL,'http://www.fasab.gov/',NULL,NULL,'true','independent','false'),
	(49278,NULL,'Federal Bureau of Investigation','FBI','http://www.fbi.gov/',NULL,52686,'false','executive','false'),
	(49281,NULL,'Federal Consulting Group',NULL,'http://www.fcg.gov',NULL,49033,'false','executive','false'),
	(49288,NULL,'Federal Executive Boards',NULL,'http://www.feb.gov/',NULL,48112,'false','independent','false'),
	(49290,NULL,'Federal Financial Institutions Examination Council',NULL,'http://www.ffiec.gov/',NULL,NULL,'true','independent','false'),
	(49292,NULL,'Federal Financing Bank',NULL,'http://www.treas.gov/ffb/',NULL,49034,'false','executive','false'),
	(49294,NULL,'Federal Geographic Data Committee',NULL,'http://www.fgdc.gov/',NULL,NULL,'true','independent','false'),
	(49296,NULL,'Federal Highway Administration',NULL,'http://www.fhwa.dot.gov/',NULL,49035,'false','executive','false'),
	(49299,NULL,'Federal Interagency Committee for the Management of Noxious and Exotic Weeds',NULL,'http://www.fs.fed.us/ficmnew/index.shtml',NULL,NULL,'true','independent','false'),
	(49300,NULL,'Federal Interagency Committee on Education',NULL,'http://www.ed.gov/about/bdscomm/list/com.html#fice',NULL,NULL,'true','independent','false'),
	(49301,NULL,'Federal Interagency Council on Statistical Policy',NULL,'http://fedstats.sites.usa.gov/',NULL,NULL,'true','independent','false'),
	(49303,NULL,'Federal Judicial Center',NULL,'http://www.fjc.gov/',NULL,NULL,'true','independent','false'),
	(49304,NULL,'Federal Laboratory Consortium for Technology Transfer',NULL,'http://www.federallabs.org/',NULL,NULL,'true','independent','false'),
	(49308,NULL,'Federal Law Enforcement Training Center',NULL,'http://www.fletc.gov/',NULL,49022,'false','executive','false'),
	(49310,NULL,'Federal Library and Information Center Committee',NULL,'http://lcweb.loc.gov/flicc/',NULL,NULL,'true','independent','false'),
	(49312,NULL,'Federal Mediation and Conciliation Service',NULL,'http://www.fmcs.gov/',NULL,NULL,'true','independent','false'),
	(49315,NULL,'Federal Motor Carrier Safety Administration','FMCSA','http://www.fmcsa.dot.gov/',NULL,49035,'false','executive','false'),
	(49318,NULL,'Federal Railroad Administration','FRA','http://www.fra.dot.gov/',NULL,49035,'false','executive','false'),
	(49320,NULL,'Federal Retirement Thrift Investment Board',NULL,'http://www.frtib.gov/',NULL,NULL,'true','independent','false'),
	(49322,NULL,'Federal Student Aid Information Center',NULL,'http://www2.ed.gov/about/offices/list/fsa/index.html',NULL,NULL,'true','independent','false'),
	(49323,NULL,'Federal Transit Administration','FTA','http://www.fta.dot.gov/',NULL,49035,'false','executive','false'),
	(49325,NULL,'Financial Management Service',NULL,'http://www.fms.treas.gov/',NULL,49034,'false','executive','false'),
	(49331,NULL,'Food Safety and Inspection Service',NULL,'http://www.fsis.usda.gov/',NULL,49015,'false','executive','false'),
	(49334,NULL,'Foreign Agricultural Service',NULL,'http://www.fas.usda.gov/',NULL,49015,'false','executive','false'),
	(49336,NULL,'Foreign Claims Settlement Commission',NULL,'http://www.usdoj.gov/fcsc/',NULL,NULL,'true','independent','false'),
	(49339,NULL,'Forest Service',NULL,'http://www.fs.fed.us/',NULL,49015,'false','executive','false'),
	(49340,NULL,'Fossil Energy',NULL,'http://www.fe.doe.gov/',NULL,49019,'false','executive','false'),
	(49341,NULL,'Fulbright Foreign Scholarship Board',NULL,'http://exchanges.state.gov/academicexchanges/fulbright/ffsb.html',NULL,NULL,'true','independent','false'),
	(49343,NULL,'U.S. Geological Survey','USGS','http://www.usgs.gov/',NULL,49033,'false','executive','false'),
	(49348,NULL,'Global Affairs','State Department','http://www.state.gov/g/',NULL,NULL,'true','independent','false'),
	(49349,NULL,'Government Accountability Office','GAO','http://www.gao.gov/',NULL,49664,'false','independent','false'),
	(49351,NULL,'Government National Mortgage Association','Ginnie Mae','http://www.ginniemae.gov',NULL,49023,'false','executive','false'),
	(49353,NULL,'Government Publishing Office',NULL,'http://www.gpo.gov/',NULL,49664,'false','independent','false'),
	(49354,NULL,'Grain Inspection, Packers and Stockyards Administration',NULL,'http://www.gipsa.usda.gov/',NULL,49450,'false','executive','false'),
	(49356,NULL,'Harry S. Truman Scholarship Foundation',NULL,'http://www.truman.gov/',NULL,NULL,'true','independent','false'),
	(49359,NULL,'Health Resources and Services Administration',NULL,'http://www.hrsa.gov/',NULL,49021,'false','executive','false'),
	(49363,NULL,'Holocaust Memorial Museum',NULL,'http://www.ushmm.org/',NULL,NULL,'true','independent','false'),
	(49367,NULL,'House Office of Inspector General',NULL,'http://www.house.gov/IG/',NULL,49371,'false','independent','false'),
	(49369,NULL,'House Office of the Clerk',NULL,'http://clerk.house.gov/',NULL,49371,'false','independent','false'),
	(49371,NULL,'U.S. House of Representatives',NULL,'http://www.house.gov/',NULL,NULL,'true','independent','false'),
	(49376,NULL,'Office of Housing',NULL,'http://www.hud.gov/offices/hsg/index.cfm',NULL,49023,'false','executive','false'),
	(49384,NULL,'Indian Arts and Crafts Board',NULL,'http://www.doi.gov/iacb/index.html',NULL,49033,'false','executive','false'),
	(49386,NULL,'Indian Health Service',NULL,'http://www.ihs.gov/',NULL,49021,'false','executive','false'),
	(49389,NULL,'Dwight D. Eisenhower School for National Security and Resource Strategy',NULL,'http://www.ndu.edu/Academics/CollegesCenters/TheEisenhowerSchool.aspx',NULL,49492,'false','executive','false'),
	(49392,NULL,'Information Resource Management College',NULL,'https://sites.google.com/a/irmcollege.net/icollege/',NULL,49492,'false','executive','false'),
	(49394,NULL,'Innovation and Improvement Office',NULL,'http://www.ed.gov/oii',NULL,49018,'false','executive','false'),
	(49395,NULL,'Institute of Education Sciences',NULL,'http://www.ed.gov/about/offices/list/ies/index.html',NULL,49018,'false','executive','false'),
	(49398,NULL,'Institute of Peace',NULL,'http://www.usip.org/',NULL,NULL,'true','independent','false'),
	(49400,NULL,'Interagency Alternative Dispute Resolution Working Group',NULL,'http://www.adr.gov/index.html',NULL,NULL,'true','independent','false'),
	(49402,NULL,'Interagency Council on Homelessness',NULL,'http://www.ich.gov',NULL,NULL,'true','independent','false'),
	(49404,NULL,'Inter-American Foundation',NULL,'http://www.iaf.gov',NULL,NULL,'true','independent','false'),
	(49409,NULL,'International Trade Administration','ITA','http://trade.gov/index.asp',NULL,52668,'false','executive','false'),
	(49412,NULL,'James Madison Memorial Fellowship Foundation',NULL,'http://www.jamesmadison.com/',NULL,NULL,'true','independent','false'),
	(49414,NULL,'Japan-United States Friendship Commission',NULL,'http://www.jusfc.gov',NULL,NULL,'true','independent','false'),
	(49416,NULL,'John F. Kennedy Center for the Performing Arts',NULL,'http://www.kennedy-center.org/',NULL,NULL,'true','independent','false'),
	(49418,NULL,'Joint Board for the Enrollment of Actuaries',NULL,'http://www.irs.gov/taxpros/actuaries/index.html',NULL,NULL,'true','independent','false'),
	(49420,NULL,'Joint Chiefs of Staff',NULL,'http://www.jcs.mil/',NULL,49229,'false','executive','false'),
	(49422,NULL,'Joint Congressional Committee on Inaugural Ceremonies',NULL,'http://inaugural.senate.gov/index.cfm',NULL,NULL,'true','independent','false'),
	(49423,NULL,'Joint Fire Science Program',NULL,'http://www.firescience.gov',NULL,NULL,'true','independent','false'),
	(49427,NULL,'Joint Forces Staff College',NULL,'http://www.jfsc.ndu.edu/',NULL,49492,'false','executive','false'),
	(49429,NULL,'National Intelligence University',NULL,'http://www.ni-u.edu/',NULL,49211,'false','executive','false'),
	(49430,NULL,'U.S. Circuit Courts of Appeal',NULL,'http://www.uscourts.gov/FederalCourts.aspx',NULL,NULL,'true','independent','false'),
	(49431,NULL,'Judicial Panel on Multidistrict Litigation',NULL,'http://www.jpml.uscourts.gov',NULL,NULL,'true','independent','false'),
	(49434,NULL,'Office of Justice Programs',NULL,'http://www.ojp.usdoj.gov/',NULL,52686,'false','executive','false'),
	(49441,NULL,'Healthy Homes and Lead Hazard Control Office',NULL,'http://www.hud.gov/offices/lead/',NULL,49023,'false','executive','false'),
	(49442,NULL,'Legal Services Corporation',NULL,'http://lsc.gov/',NULL,NULL,'true','independent','false'),
	(49444,NULL,'U.S. Marine Corps',NULL,'http://www.usmc.mil/',NULL,49561,'false','executive','false'),
	(49446,NULL,'Marine Mammal Commission',NULL,'http://www.mmc.gov/',NULL,NULL,'true','independent','false'),
	(49448,NULL,'Maritime Administration','MARAD','http://www.marad.dot.gov/',NULL,49035,'false','executive','false'),
	(49450,NULL,'Marketing and Regulatory Programs','Agriculture Department','http://www.usda.gov/wps/portal/usda/usdahome?contentid=missionarea_MRP.xml',NULL,49015,'false','executive','false'),
	(49451,NULL,'Marshals Service',NULL,'http://www.usdoj.gov/marshals/',NULL,52686,'false','executive','false'),
	(49457,NULL,'Migratory Bird Conservation Commission',NULL,'http://www.fws.gov/refuges/realty/mbcc.html',NULL,48057,'false','executive','false'),
	(49459,NULL,'Military Postal Service Agency',NULL,'http://hqdainet.army.mil/mpsa/main.htm',NULL,49229,'false','executive','false'),
	(49460,NULL,'Millennium Challenge Corporation',NULL,'http://www.mcc.gov',NULL,NULL,'true','independent','false'),
	(49462,NULL,'Mine Safety and Health Administration',NULL,'http://www.msha.gov/',NULL,49028,'false','executive','false'),
	(49464,NULL,'Minority Business Development Agency',NULL,'http://www.mbda.gov/',NULL,52668,'false','executive','false'),
	(49468,NULL,'Missile Defense Agency','MDA','http://www.mda.mil',NULL,49229,'false','executive','false'),
	(49470,NULL,'Mississippi River Commission',NULL,'http://www.mvd.usace.army.mil/About/MississippiRiverCommission%28MRC%29.aspx',NULL,NULL,'true','independent','false'),
	(49473,NULL,'Morris K. Udall and Stewart L. Udall Foundation',NULL,'http://www.udall.gov/',NULL,NULL,'true','independent','false'),
	(49475,NULL,'Multifamily Housing Office',NULL,'http://portal.hud.gov/hudportal/HUD?src=/program_offices/housing/mfh',NULL,49023,'false','executive','false'),
	(49476,NULL,'National Aeronautics and Space Administration','NASA','http://www.nasa.gov',NULL,NULL,'true','independent','true'),
	(49479,NULL,'National Agricultural Statistics Service',NULL,'http://www.nass.usda.gov',NULL,49015,'false','executive','false'),
	(49481,NULL,'National AIDS Policy Office',NULL,'http://www.whitehouse.gov/onap/aids.html',NULL,49235,'false','executive','false'),
	(49483,NULL,'National Archives and Records Administration','NARA','http://www.archives.gov/index.html',NULL,NULL,'true','independent','false'),
	(49484,NULL,'National Bipartisan Commission on the Future of Medicare',NULL,'http://rs9.loc.gov/medicare/index.html',NULL,NULL,'true','independent','false'),
	(49488,NULL,'National Commission on Fiscal Responsibility and Reform',NULL,'http://www.fiscalcommission.gov',NULL,NULL,'true','independent','false'),
	(49489,NULL,'National Constitution Center',NULL,'http://www.constitutioncenter.org/',NULL,NULL,'true','independent','false'),
	(49490,NULL,'National Counterintelligence Executive, Office of',NULL,'http://www.ncix.gov/',NULL,49595,'false','independent','false'),
	(49492,NULL,'National Defense University',NULL,'http://www.ndu.edu/',NULL,49229,'false','executive','false'),
	(49494,NULL,'National Drug Intelligence Center',NULL,'http://www.usdoj.gov/ndic/index.htm',NULL,52686,'false','executive','false'),
	(49496,NULL,'National Economic Council',NULL,'http://www.whitehouse.gov/nec/index.html',NULL,NULL,'true','executive','false'),
	(49502,NULL,'National Gallery of Art',NULL,'http://www.nga.gov/',NULL,NULL,'true','independent','false'),
	(49504,NULL,'National Geospatial-Intelligence Agency',NULL,'http://www.nga.mil/',NULL,49229,'false','executive','false'),
	(49506,NULL,'National Guard',NULL,'http://www.nationalguard.mil/',NULL,NULL,'true','independent','false'),
	(49512,NULL,'National Indian Gaming Commission',NULL,'http://www.nigc.gov/',NULL,NULL,'true','independent','false'),
	(49515,NULL,'National Institute of Justice',NULL,'http://www.ojp.usdoj.gov/nij/welcome.html',NULL,49434,'false','executive','false'),
	(49517,NULL,'National Institute of Standards and Technology','NIST','http://www.nist.gov/',NULL,52668,'false','executive','false'),
	(49520,NULL,'National Interagency Fire Center',NULL,'http://www.nifc.gov/',NULL,NULL,'true','independent','false'),
	(49522,NULL,'National Laboratories','Energy Department','http://www.energy.gov/organization/labs-techcenters.htm',NULL,49019,'false','executive','false'),
	(49523,NULL,'National Labor Relations Board','NLRB','http://www.nlrb.gov/',NULL,NULL,'true','independent','false'),
	(49524,NULL,'National Marine Fisheries Service',NULL,'http://www.nmfs.noaa.gov/',NULL,49530,'false','executive','false'),
	(49526,NULL,'National Mediation Board',NULL,'http://www.nmb.gov/',NULL,NULL,'true','independent','false'),
	(49528,NULL,'National Nuclear Security Administration',NULL,'http://www.nnsa.doe.gov/',NULL,49019,'false','executive','false'),
	(49530,NULL,'National Oceanic and Atmospheric Administration','NOAA','http://www.noaa.gov/',NULL,52668,'false','executive','false'),
	(49533,NULL,'National Ocean Service',NULL,'http://oceanservice.noaa.gov',NULL,49530,'false','executive','false'),
	(49536,NULL,'National Park Foundation',NULL,'http://www.nationalparks.org/',NULL,NULL,'true','independent','false'),
	(49539,NULL,'National Park Service',NULL,'http://www.nps.gov/',NULL,49033,'false','executive','false'),
	(49542,NULL,'National Reconnaissance Office',NULL,'http://www.nro.gov/',NULL,NULL,'true','independent','false'),
	(49546,NULL,'National Security Agency','NSA','http://www.nsa.gov/',NULL,49229,'false','executive','false'),
	(49548,NULL,'National Security Council',NULL,'http://www.whitehouse.gov/nsc/index.html',NULL,NULL,'true','executive','false'),
	(49549,NULL,'National Technical Information Service',NULL,'http://www.ntis.gov/',NULL,52668,'false','executive','false'),
	(49551,NULL,'National Telecommunications and Information Administration',NULL,'http://www.ntia.doc.gov/',NULL,52668,'false','executive','false'),
	(49555,NULL,'National War College',NULL,'http://www.ndu.edu/Academics/CollegesCenters/NationalWarCollege.aspx',NULL,49492,'false','executive','false'),
	(49557,NULL,'National Weather Service','NOAA','http://www.nws.noaa.gov/',NULL,49530,'false','executive','false'),
	(49560,NULL,'Natural Resources Conservation Service',NULL,'http://www.nrcs.usda.gov/wps/portal/nrcs/home',NULL,49015,'false','executive','false'),
	(49561,NULL,'U.S. Navy',NULL,'http://www.navy.mil/',NULL,49229,'false','executive','false'),
	(49565,NULL,'Northern Command',NULL,'http://www.northcom.mil/',NULL,49726,'false','executive','false'),
	(49567,NULL,'Northwest Power and Conservation Council',NULL,'http://www.nwcouncil.org/',NULL,NULL,'true','independent','false'),
	(49569,NULL,'Nuclear Energy, Science and Technology',NULL,'http://www.ne.doe.gov/',NULL,49019,'false','executive','false'),
	(49571,NULL,'Nuclear Waste Technical Review Board',NULL,'http://www.nwtrb.gov/',NULL,NULL,'true','independent','false'),
	(49573,NULL,'Oak Ridge National Laboratory',NULL,'http://www.oro.doe.gov/',NULL,49522,'false','executive','false'),
	(49577,NULL,'Occupational Safety and Health Review Commission',NULL,'http://www.oshrc.gov/index.html',NULL,NULL,'true','independent','false'),
	(49579,NULL,'Office of Compliance',NULL,'http://www.compliance.gov',NULL,49664,'false','independent','false'),
	(49584,NULL,'Office of Management and Budget','OMB','http://www.whitehouse.gov/omb/',NULL,NULL,'true','executive','false'),
	(49586,NULL,'Office of National Drug Control Policy','ONDCP','http://www.whitehouse.gov/ondcp',NULL,NULL,'true','executive','false'),
	(49588,NULL,'Office of Refugee Resettlement',NULL,'http://www.acf.hhs.gov/programs/orr/',NULL,47994,'false','executive','false'),
	(49590,NULL,'Office of Science and Technology Policy',NULL,'http://www.ostp.gov/',NULL,NULL,'true','executive','false'),
	(49592,NULL,'Office of Scientific and Technical Information',NULL,'http://www.osti.gov/',NULL,49658,'false','executive','false'),
	(49593,NULL,'Office of Special Counsel',NULL,'http://www.osc.gov/',NULL,NULL,'true','independent','false'),
	(49595,NULL,'Office of the Director of National Intelligence',NULL,'http://www.dni.gov',NULL,NULL,'true','independent','false'),
	(49597,NULL,'Open World Leadership Center',NULL,'http://www.openworld.gov',NULL,49664,'false','independent','false'),
	(49601,NULL,'Pacific Command',NULL,'http://www.pacom.mil/',NULL,49726,'false','executive','false'),
	(49604,NULL,'Office of the Pardon Attorney',NULL,'http://www.usdoj.gov/pardon/index.html',NULL,52686,'false','executive','false'),
	(49606,NULL,'Parole Commission','Justice Department','http://www.usdoj.gov/uspc/',NULL,52686,'false','executive','false'),
	(49614,NULL,'Pentagon Force Protection Agency',NULL,'http://www.pfpa.mil/',NULL,49229,'false','executive','false'),
	(49616,NULL,'Pipeline and Hazardous Materials Safety Administration',NULL,'http://www.phmsa.dot.gov/',NULL,49035,'false','executive','false'),
	(49618,NULL,'Policy Development and Research','HUD','http://www.huduser.org',NULL,49023,'false','executive','false'),
	(49620,NULL,'Political Affairs','State Department','http://www.state.gov/p/',NULL,NULL,'true','independent','false'),
	(49621,NULL,'Postal Regulatory Commission',NULL,'http://www.prc.gov',NULL,NULL,'true','independent','false'),
	(49624,NULL,'Power Administrations',NULL,'http://www.energy.gov/organization/powermarketingadmin.htm',NULL,49019,'false','executive','false'),
	(49625,NULL,'Presidio Trust',NULL,'http://www.presidio.gov',NULL,NULL,'true','independent','false'),
	(49627,NULL,'Prisoner of War/Missing Personnel Office',NULL,'http://www.dtic.mil/dpmo/',NULL,49229,'false','executive','false'),
	(49629,NULL,'Public and Indian Housing',NULL,'http://www.hud.gov/offices/pih/index.cfm',NULL,49023,'false','executive','false'),
	(49632,NULL,'Public Diplomacy and Public Affairs','State Department','http://www.state.gov/r/',NULL,NULL,'true','independent','false'),
	(49635,NULL,'Radio Free Asia','RFA','http://www.rfa.org/',NULL,49109,'false','independent','false'),
	(49637,NULL,'Radio Free Europe/Radio Liberty','RFE/RL','http://www.rferl.org/',NULL,49109,'false','independent','false'),
	(49642,NULL,'Regulatory Information Service Center',NULL,'http://www.reginfo.gov/',NULL,49584,'false','executive','false'),
	(49644,NULL,'Rehabilitation Services Administration','Education Department','http://www.ed.gov/about/offices/list/osers/rsa/index.html?exp=0',NULL,48121,'false','executive','false'),
	(49647,NULL,'Research and Innovative Technology Administration',NULL,'http://www.rita.dot.gov/',NULL,49035,'false','executive','false'),
	(49649,NULL,'Risk Management Agency','Agriculture Department','http://www.rma.usda.gov/',NULL,49015,'false','executive','false'),
	(49650,NULL,'Rural Business and Cooperative Programs',NULL,'http://www.rurdev.usda.gov/LP_Subject_BusinessAndCooperativeAssistance.html',NULL,49653,'false','executive','false'),
	(49653,NULL,'Rural Development',NULL,'http://www.rurdev.usda.gov/',NULL,49015,'false','executive','false'),
	(49654,NULL,'Rural Housing Service',NULL,'http://www.rurdev.usda.gov/LP_Subject_HousingAndCommunityAssistance.html',NULL,49653,'false','executive','false'),
	(49655,NULL,'Rural Utilities Service',NULL,'http://www.rurdev.usda.gov/Utilities_Assistance.html',NULL,49653,'false','executive','false'),
	(49656,NULL,'Saint Lawrence Seaway Development Corporation',NULL,'http://www.seaway.dot.gov/',NULL,49035,'false','executive','false'),
	(49658,NULL,'Science Office','Energy Department','http://science.energy.gov/',NULL,49019,'false','executive','false'),
	(49660,NULL,'Secret Service',NULL,'http://www.secretservice.gov/index.shtml',NULL,49022,'false','executive','false'),
	(49664,NULL,'U.S. Senate',NULL,'http://www.senate.gov/',NULL,NULL,'true','independent','false'),
	(49668,NULL,'Smithsonian Institution',NULL,'http://www.si.edu/',NULL,NULL,'true','independent','false'),
	(49670,NULL,'Social Security Advisory Board',NULL,'http://www.ssab.gov/',NULL,NULL,'true','independent','false'),
	(49672,NULL,'Southeastern Power Administration',NULL,'http://199.44.84.82/',NULL,49624,'false','executive','false'),
	(49674,NULL,'Southern Command',NULL,'http://www.southcom.mil/Pages/Default.aspx',NULL,49726,'false','executive','false'),
	(49676,NULL,'Southwestern Power Administration',NULL,'http://www.swpa.gov/',NULL,49624,'false','executive','false'),
	(49678,NULL,'Special Forces Operations Command',NULL,'http://www.socom.mil/',NULL,49726,'false','executive','false'),
	(49681,NULL,'State Justice Institute',NULL,'http://www.sji.gov/about.php',NULL,NULL,'true','independent','false'),
	(49684,NULL,'Stennis Center for Public Service',NULL,'http://www.stennis.gov/',NULL,49664,'false','independent','false'),
	(49685,NULL,'Strategic Command',NULL,'http://www.stratcom.mil/',NULL,49726,'false','executive','false'),
	(49687,NULL,'Substance Abuse and Mental Health Services Administration',NULL,'http://www.samhsa.gov/',NULL,49021,'false','executive','false'),
	(49688,NULL,'Supreme Court of the United States',NULL,'http://www.supremecourtus.gov/',NULL,NULL,'true','independent','false'),
	(49690,NULL,'Surface Mining, Reclamation and Enforcement',NULL,'http://www.osmre.gov/',NULL,49033,'false','executive','false'),
	(49691,NULL,'Surface Transportation Board',NULL,'http://www.stb.dot.gov/',NULL,49035,'false','executive','false'),
	(49692,NULL,'Susquehanna River Basin Commission',NULL,'http://www.srbc.net/',NULL,NULL,'true','independent','false'),
	(49694,NULL,'Tax Court',NULL,'http://www.ustaxcourt.gov/',NULL,NULL,'true','independent','false'),
	(49696,NULL,'Taxpayer Advocacy Panel',NULL,'http://www.improveirs.org',NULL,49034,'false','executive','false'),
	(49699,NULL,'Transportation Command',NULL,'http://www.transcom.mil',NULL,49726,'false','executive','false'),
	(49706,NULL,'TRICARE Management',NULL,'http://www.tricare.mil/',NULL,49229,'false','executive','false'),
	(49709,NULL,'U.S. Capitol Visitor Center',NULL,'http://www.visitthecapitol.gov',NULL,49088,'false','independent','false'),
	(49711,NULL,'U.S. Immigration and Customs Enforcement',NULL,'http://www.ice.gov/',NULL,49022,'false','executive','false'),
	(49712,NULL,'U.S. International Trade Commission',NULL,'http://www.usitc.gov/',NULL,NULL,'true','independent','false'),
	(49713,NULL,'U.S. Military Academy, West Point',NULL,'http://www.usma.edu/',NULL,49229,'false','executive','false'),
	(49715,NULL,'U.S. Mission to the United Nations',NULL,'http://www.usunnewyork.usmission.gov/',NULL,49030,'false','executive','false'),
	(49717,NULL,'U.S. National Central Bureau - Interpol','Justice Department','http://www.usdoj.gov/usncb/',NULL,52686,'false','executive','false'),
	(49719,NULL,'U.S. Sentencing Commission',NULL,'http://www.ussc.gov/',NULL,NULL,'true','independent','false'),
	(49721,NULL,'U.S. Trade and Development Agency',NULL,'http://www.ustda.gov/',NULL,NULL,'true','independent','false'),
	(49724,NULL,'U.S. Trade Representative',NULL,'http://www.ustr.gov/',NULL,NULL,'true','executive','false'),
	(49726,NULL,'Unified Combatant Commands','Defense Department','http://www.defenselink.mil/specials/unifiedcommand/',NULL,49229,'false','executive','false'),
	(49727,NULL,'Uniformed Services University of the Health Sciences',NULL,'http://www.usuhs.mil/',NULL,49229,'false','executive','false'),
	(49730,NULL,'Veterans\' Employment and Training Service',NULL,'http://www.dol.gov/vets/',NULL,49028,'false','executive','false'),
	(49732,NULL,'Vietnam Education Foundation',NULL,'http://www.vef.gov',NULL,NULL,'true','independent','false'),
	(49736,NULL,'Veterans Day National Committee',NULL,'http://www1.va.gov/opa/vetsday/vdnc.asp',NULL,48027,'false','executive','false'),
	(49737,NULL,'Washington Headquarters Services',NULL,'http://www.whs.mil/',NULL,49229,'false','executive','false'),
	(49740,NULL,'Western Area Power Administration',NULL,'http://ww2.wapa.gov/sites/western/Pages/default.aspx',NULL,49624,'false','executive','false'),
	(49743,NULL,'White House',NULL,'http://www.whitehouse.gov/',NULL,NULL,'true','independent','false'),
	(49744,NULL,'White House Commission on Presidential Scholars',NULL,'http://www.ed.gov/programs/psp/commission.html?exp=0',NULL,49018,'false','executive','false'),
	(49747,NULL,'White House Office of Administration',NULL,'http://www.whitehouse.gov/oa/index.html',NULL,NULL,'true','executive','false'),
	(49748,NULL,'Women\'s Bureau','Labor Department','http://www.dol.gov/wb/',NULL,49028,'false','executive','false'),
	(49749,NULL,'Woodrow Wilson International Center for Scholars',NULL,'http://www.wilsoncenter.org',NULL,NULL,'true','independent','false'),
	(52580,NULL,'Advisory Council on Historic Preservation',NULL,'http://www.achp.gov/',NULL,NULL,'true','independent','false'),
	(52581,NULL,'African Development Foundation',NULL,'http://www.adf.gov',NULL,NULL,'true','independent','false'),
	(52583,NULL,'U.S. Agency for International Development','USAID','http://www.usaid.gov/',NULL,NULL,'true','independent','true'),
	(52584,NULL,'American Battle Monuments Commission',NULL,'http://www.abmc.gov/',NULL,NULL,'true','independent','false'),
	(52586,NULL,'AmeriCorps',NULL,'http://www.americorps.gov/',NULL,52593,'false','independent','false'),
	(52588,NULL,'Appalachian Regional Commission',NULL,'http://www.arc.gov/',NULL,NULL,'true','independent','false'),
	(52590,NULL,'Central Intelligence Agency','CIA','http://www.cia.gov/',NULL,NULL,'true','independent','false'),
	(52591,NULL,'Chemical Safety and Hazard Investigation Board',NULL,'http://www.csb.gov',NULL,NULL,'true','independent','false'),
	(52592,NULL,'U.S. Commission of Fine Arts',NULL,'http://www.cfa.gov/',NULL,NULL,'true','independent','false'),
	(52593,NULL,'Corporation for National and Community Service',NULL,'http://www.nationalservice.gov/',NULL,NULL,'true','independent','false'),
	(52595,NULL,'Defense Finance and Accounting Service','DFAS','http://www.dfas.mil/',NULL,49229,'false','executive','false'),
	(52599,NULL,'Defense Logistics Agency','DLA','http://www.dla.mil',NULL,49229,'false','executive','false'),
	(52601,NULL,'Defense Nuclear Facilities Safety Board',NULL,'http://www.dnfsb.gov/',NULL,NULL,'true','independent','false'),
	(52603,NULL,'Export-Import Bank of the United States',NULL,'http://www.exim.gov/index.cfm',NULL,NULL,'true','independent','false'),
	(52605,NULL,'Farm Credit Administration',NULL,'http://www.fca.gov/',NULL,NULL,'true','independent','false'),
	(52607,NULL,'Federal Election Commission',NULL,'http://www.fec.gov/',NULL,NULL,'true','independent','false'),
	(52608,NULL,'Federal Energy Regulatory Commission',NULL,'http://www.ferc.gov/',NULL,49019,'false','executive','false'),
	(52610,NULL,'Federal Home Loan Mortgage Corporation','Freddie Mac','http://www.freddiemac.com',NULL,52611,'false','independent','false'),
	(52611,NULL,'Federal Housing Finance Agency',NULL,'http://www.fhfa.gov',NULL,NULL,'true','independent','false'),
	(52613,NULL,'Federal Labor Relations Authority',NULL,'http://www.flra.gov',NULL,NULL,'true','independent','false'),
	(52615,NULL,'Federal Maritime Commission',NULL,'http://www.fmc.gov/',NULL,NULL,'true','independent','false'),
	(52617,NULL,'Federal Mine Safety and Health Review Commission',NULL,'http://www.fmshrc.gov/',NULL,NULL,'true','independent','false'),
	(52619,NULL,'Federal National Mortgage Association','Fannie Mae','http://www.fanniemae.com/',NULL,52611,'false','independent','false'),
	(52626,NULL,'Institute of Museum and Library Services',NULL,'http://www.imls.gov/',NULL,NULL,'true','independent','false'),
	(52628,NULL,'Library of Congress','LOC','http://www.loc.gov/',NULL,49664,'false','independent','false'),
	(52629,NULL,'Medicare Payment Advisory Commission',NULL,'http://www.medpac.gov/',NULL,NULL,'true','independent','false'),
	(52630,NULL,'Merit Systems Protection Board',NULL,'http://www.mspb.gov/',NULL,NULL,'true','independent','false'),
	(52633,NULL,'National Capital Planning Commission',NULL,'http://www.ncpc.gov/',NULL,NULL,'true','independent','false'),
	(52634,NULL,'National Endowment for the Arts',NULL,'http://www.arts.gov/',NULL,NULL,'true','independent','false'),
	(52636,NULL,'National Endowment for the Humanities',NULL,'http://www.neh.gov',NULL,NULL,'true','independent','false'),
	(52640,NULL,'National Science Foundation','NSF','http://www.nsf.gov/',NULL,NULL,'true','independent','true'),
	(52641,NULL,'National Transportation Safety Board',NULL,'http://www.ntsb.gov/',NULL,NULL,'true','independent','false'),
	(52645,NULL,'Nuclear Regulatory Commission','NRC','http://www.nrc.gov/',NULL,NULL,'true','independent','true'),
	(52646,NULL,'Office of Government Ethics',NULL,'http://www.oge.gov/',NULL,NULL,'true','independent','false'),
	(52651,NULL,'Overseas Private Investment Corporation',NULL,'http://www.opic.gov/',NULL,NULL,'true','independent','false'),
	(52652,NULL,'Peace Corps',NULL,'http://www.peacecorps.gov/about/',NULL,NULL,'true','independent','false'),
	(52654,NULL,'President\'s Council on Physical Fitness and Sports',NULL,'http://www.fitness.gov/',NULL,NULL,'true','independent','false'),
	(52655,NULL,'Public Records/Disclosure Office',NULL,'http://www.fec.gov/pubrec/publicrecordsoffice.shtml',NULL,NULL,'true','independent','false'),
	(52657,NULL,'Railroad Retirement Board','RRB','http://www.rrb.gov/default.asp',NULL,NULL,'true','independent','false'),
	(52658,NULL,'Selective Service System','SSS','http://www.sss.gov/',NULL,NULL,'true','independent','false'),
	(52660,NULL,'Tennessee Valley Authority',NULL,'http://www.tva.gov/',NULL,NULL,'true','independent','false'),
	(52663,NULL,'U.S. Access Board',NULL,'http://www.access-board.gov/',NULL,NULL,'true','independent','false'),
	(52666,NULL,'U.S. Election Assistance Commission','EAC','http://www.eac.gov/',NULL,NULL,'true','independent','false'),
	(52668,NULL,'Department of Commerce','DOC','http://www.commerce.gov/',NULL,NULL,'true','executive','true'),
	(52676,NULL,'Education Resources Information Center','ERIC','http://www.eric.ed.gov/',NULL,49395,'false','executive','false'),
	(52678,NULL,'Center for Food Safety and Applied Nutrition',NULL,'http://www.fda.gov/AboutFDA/CentersOffices/OfficeofFoods/CFSAN/default.htm',NULL,48058,'false','executive','false'),
	(52681,NULL,'National Institute of Occupational Safety and Health',NULL,'http://www.cdc.gov/niosh/',NULL,48013,'false','executive','false'),
	(52682,NULL,'Antitrust Division',NULL,'http://www.justice.gov/atr/index.html',NULL,52686,'false','executive','false'),
	(52683,NULL,'Bureau of Justice Statistics',NULL,'http://bjs.ojp.usdoj.gov/',NULL,49434,'false','executive','false'),
	(52686,NULL,'Department of Justice','DOJ','http://www.usdoj.gov/',NULL,NULL,'true','executive','true'),
	(52688,NULL,'Drug Enforcement Administration',NULL,'http://www.justice.gov/dea/',NULL,52686,'false','executive','false'),
	(52691,NULL,'Office of Juvenile Justice and Delinquency Prevention',NULL,'http://www.ojjdp.gov/index.html',NULL,49434,'false','executive','false'),
	(52693,NULL,'Employment and Training Administration',NULL,'http://www.doleta.gov/',NULL,49028,'false','executive','false'),
	(55826,NULL,'AIDsinfo',NULL,NULL,NULL,NULL,'true','independent','false'),
	(55835,NULL,'Americans with Disabilities Act Information Line',NULL,'http://www.ada.gov',NULL,NULL,'true','independent','false'),
	(55847,NULL,'Federal Citizen Information Center',NULL,'http://gsa.gov/portal/content/101085',NULL,49048,'false','independent','false'),
	(55853,NULL,'HIV/AIDS Prevention',NULL,NULL,NULL,NULL,'true','independent','false'),
	(55854,NULL,'Indoor Environments Division',NULL,NULL,NULL,NULL,'true','independent','false'),
	(55875,NULL,'National Cancer Institute','NCI',NULL,NULL,NULL,'true','independent','false'),
	(55887,NULL,'Office for Civil Rights, Department of Health and Human Services',NULL,'http://www.hhs.gov/ocr',NULL,NULL,'true','independent','false'),
	(55890,NULL,'Office of Manufactured Housing Programs',NULL,NULL,NULL,NULL,'true','independent','false'),
	(55892,NULL,'Office of RESPA and Interstate Land Sales',NULL,NULL,NULL,49023,'false','executive','false'),
	(55896,NULL,'Seafood Inspection Program',NULL,NULL,NULL,NULL,'true','independent','false'),
	(55897,NULL,'U.S. Citizenship and Immigration Services',NULL,'http://www.uscis.gov',NULL,49022,'false','executive','false'),
	(55927,NULL,'U.S. Customs and Border Protection',NULL,'http://www.cbp.gov/',NULL,49022,'false','executive','false'),
	(55928,NULL,'Weights and Measures Division',NULL,'http://www.nist.gov/pml/wmd/',NULL,49517,'false','executive','false'),
	(61787,NULL,'Medicaid and CHIP Payment and Access Commission',NULL,'http://www.macpac.gov',NULL,NULL,'true','independent','false'),
	(68880,NULL,'Federal Voting Assistance Program',NULL,'http://www.fvap.gov/',NULL,49229,'false','executive','false'),
	(72714,NULL,'U.S. Capitol Police',NULL,'http://www.house.gov/content/learn/partners/capitol_police.php',NULL,49664,'false','independent','false'),
	(72913,NULL,'Farm Credit System Insurance Corporation',NULL,'http://www.fcsic.gov/index.html',NULL,NULL,'true','independent','false'),
	(85112,NULL,'Joint Program Executive Office for Chemical and Biological Defense ',NULL,'http://www.jpeocbd.osd.mil/',NULL,49096,'false','executive','false'),
	(85122,NULL,'Bureau of Ocean Energy Management','BOEM','http://www.boem.gov/',NULL,49033,'false','executive','false'),
	(85146,NULL,'Bureau of Safety and Environmental Enforcement','BSEE','http://www.bsee.gov/',NULL,49033,'false','executive','false'),
	(85148,NULL,'Office of Natural Resources Revenue',NULL,'http://www.onrr.gov/',NULL,49033,'false','executive','false'),
	(85230,NULL,'Federal Protective Service',NULL,'http://www.dhs.gov/federal-protective-service',NULL,49022,'false','executive','false'),
	(85304,NULL,'U.S. Air Force Reserve Command',NULL,'http://www.afrc.af.mil/',NULL,49080,'false','executive','false'),
	(88975,NULL,'Office of Servicemember Affairs',NULL,'http://www.consumerfinance.gov/servicemembers/',NULL,49113,'false','independent','false'),
	(88999,NULL,'Bureau of the Fiscal Service',NULL,'http://www.fiscal.treasury.gov',NULL,49034,'false','executive','false'),
	(89194,NULL,'National Institute of Corrections',NULL,'http://nicic.gov',NULL,49126,'false','executive','false'),
	(91390,NULL,'Council of the Inspectors General on Integrity and Efficiency',NULL,'http://www.ignet.gov',NULL,NULL,'true','independent','false'),
	(91587,NULL,'Bureau of Engraving and Printing','BEP','http://www.moneyfactory.gov',NULL,49034,'false','executive','false'),
	(91727,NULL,'Defense Finance and Accounting Service Garnishment Operations Center',NULL,'https://www.dfas.mil/dfas/garnishment.html',NULL,52595,'false','executive','false'),
	(91741,NULL,'Defense Finance and Accounting Service Out-of-Service Debt Management Center',NULL,'https://www.dfas.mil/debtandclaims.html',NULL,52595,'false','executive','false'),
	(91836,NULL,'Administration for Community Living',NULL,'http://www.acl.gov',NULL,49021,'false','executive','false'),
	(92601,NULL,'Bureau of Consular Affairs',NULL,'http://travel.state.gov/',NULL,49030,'false','executive','false');
