---
name: Dashboard crawl (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * *'

jobs:
  dashboard-crawl-staging:
    name: dashboard crawl (staging)
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crawl daily (stage)
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@cli-v7
        with:
          command: ./bin/cf-crawl-daily.sh dashboard-stage
          cf_org: gsa-datagov
          cf_space: staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
  dashboard-crawl-prod:
    name: dashboard crawl (production)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crawl daily (prod)
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@cli-v7
        with:
          command: ./bin/cf-crawl-daily.sh dashboard
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
